# Generated by Django 4.2.29 on 2026-03-08 10:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "favorite_type",
                    models.CharField(
                        choices=[
                            ("resource", "Resource"),
                            ("personal_file", "Personal File"),
                            ("folder", "Folder"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "personal_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="resources.personalresource",
                    ),
                ),
                (
                    "personal_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="resources.personalfolder",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="resources.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="favorites_f_created_49a632_idx"
                    ),
                    models.Index(
                        fields=["user", "favorite_type", "-created_at"],
                        name="favorites_f_user_id_bdf8a8_idx",
                    ),
                ],
                "unique_together": {
                    ("user", "personal_folder"),
                    ("user", "resource"),
                    ("user", "personal_file"),
                },
            },
        ),
    ]
