# Generated by Django 4.2.29 on 2026-03-25 13:41

import apps.referrals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='email',
            field=models.EmailField(help_text='Email of the referred user (before registration)', max_length=254),
        ),
        migrations.AlterField(
            model_name='referral',
            name='subscribed_at',
            field=models.DateTimeField(blank=True, help_text='When the referee subscribed to premium', null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(db_index=True, default=apps.referrals.models.generate_unique_referral_code, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the referral code expires', null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='max_uses',
            field=models.IntegerField(default=100, help_text='Maximum number of times this code can be used'),
        ),
        migrations.AlterField(
            model_name='rewardtier',
            name='badge',
            field=models.CharField(blank=True, help_text='Badge identifier to grant', max_length=100),
        ),
        migrations.AlterField(
            model_name='rewardtier',
            name='min_referrals',
            field=models.IntegerField(help_text='Minimum number of referrals required for this tier'),
        ),
    ]
