# Generated by Django 4.2.29 on 2026-03-25 13:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('content', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('folder', models.CharField(blank=True, default='default', max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('is_collaborative', models.BooleanField(default=False)),
                ('lock_timeout', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('version_number', models.PositiveIntegerField()),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_versions', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='notes.note')),
            ],
            options={
                'db_table': 'note_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['note', '-version_number'], name='note_versio_note_id_530ae0_idx')],
            },
        ),
        migrations.CreateModel(
            name='NoteShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'Can Edit'), ('admin', 'Admin')], default='view', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('can_share', models.BooleanField(default=False)),
                ('can_copy', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note_shares',
                'indexes': [models.Index(fields=['note', 'is_active'], name='note_shares_note_id_027beb_idx'), models.Index(fields=['user', 'is_active'], name='note_shares_user_id_a551fc_idx')],
                'unique_together': {('note', 'user')},
            },
        ),
        migrations.CreateModel(
            name='NotePresence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.CharField(choices=[('viewing', 'Viewing'), ('editing', 'Editing'), ('idle', 'Idle')], default='viewing', max_length=20)),
                ('cursor_position', models.PositiveIntegerField(default=0)),
                ('cursor_selection', models.JSONField(default=dict)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note_presence',
                'indexes': [models.Index(fields=['note', 'is_online'], name='note_presen_note_id_231e59_idx')],
                'unique_together': {('note', 'user')},
            },
        ),
        migrations.CreateModel(
            name='NoteLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lock_type', models.CharField(default='edit', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note_locks',
                'indexes': [models.Index(fields=['note', 'expires_at'], name='note_locks_note_id_4573b2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'folder'], name='study_notes_owner_i_3d0a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['status', '-updated_at'], name='study_notes_status_f7ef83_idx'),
        ),
    ]
