# Generated by Django 4.2.29 on 2026-03-08 10:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookmarks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("viewed_resource", "Viewed Resource"),
                            ("opened_personal_file", "Opened Personal File"),
                            ("downloaded_resource", "Downloaded Resource"),
                            ("downloaded_personal_file", "Downloaded Personal File"),
                            ("bookmarked_resource", "Bookmarked Resource"),
                            ("created_resource", "Created Resource"),
                            ("updated_resource", "Updated Resource"),
                            ("commented", "Commented"),
                            ("rated", "Rated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "bookmark",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="bookmarks.bookmark",
                    ),
                ),
                (
                    "personal_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="resources.personalresource",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="resources.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recent Activity",
                "verbose_name_plural": "Recent Activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="activity_re_created_de33e7_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="activity_re_user_id_dc7671_idx",
                    ),
                    models.Index(
                        fields=["user", "activity_type", "-created_at"],
                        name="activity_re_user_id_b79be2_idx",
                    ),
                ],
            },
        ),
    ]
