# Generated by Django 4.2.29 on 2026-03-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='activity_type',
            field=models.CharField(choices=[('viewed_resource', 'Viewed Resource'), ('opened_personal_file', 'Opened Personal File'), ('downloaded_resource', 'Downloaded Resource'), ('downloaded_personal_file', 'Downloaded Personal File'), ('bookmarked_resource', 'Bookmarked Resource'), ('created_resource', 'Created Resource'), ('updated_resource', 'Updated Resource'), ('commented', 'Commented'), ('rated', 'Rated'), ('shared_resource', 'Shared Resource')], max_length=50),
        ),
    ]
