# Generated by Codex on 2026-03-25

import apps.core.encryption
from django.db import migrations


USER_FIELDS = [
    "phone_number",
    "phone",
    "student_id",
    "bio",
    "date_of_birth",
    "suspension_reason",
]

PROFILE_FIELDS = [
    "bio",
    "date_of_birth",
    "address",
    "city",
    "country",
    "facebook",
    "twitter",
    "linkedin",
]

PASSKEY_FIELDS = [
    "public_key",
    "aaguid",
]


def _reencrypt_accounts_data(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Profile = apps.get_model("accounts", "Profile")
    UserPasskey = apps.get_model("accounts", "UserPasskey")

    for user in User.objects.all().iterator(chunk_size=100):
        for field_name in USER_FIELDS:
            setattr(user, field_name, getattr(user, field_name))
        user.save(update_fields=USER_FIELDS)

    for profile in Profile.objects.all().iterator(chunk_size=100):
        for field_name in PROFILE_FIELDS:
            setattr(profile, field_name, getattr(profile, field_name))
        profile.save(update_fields=PROFILE_FIELDS)

    for passkey in UserPasskey.objects.all().iterator(chunk_size=100):
        for field_name in PASSKEY_FIELDS:
            setattr(passkey, field_name, getattr(passkey, field_name))
        passkey.save(update_fields=PASSKEY_FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userpasskey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=apps.core.encryption.EncryptedCharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=apps.core.encryption.EncryptedCharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="student_id",
            field=apps.core.encryption.EncryptedCharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=apps.core.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=apps.core.encryption.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="suspension_reason",
            field=apps.core.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=apps.core.encryption.EncryptedTextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=apps.core.encryption.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=apps.core.encryption.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=apps.core.encryption.EncryptedCharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=apps.core.encryption.EncryptedCharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="facebook",
            field=apps.core.encryption.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter",
            field=apps.core.encryption.EncryptedCharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin",
            field=apps.core.encryption.EncryptedCharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userpasskey",
            name="public_key",
            field=apps.core.encryption.EncryptedTextField(
                help_text="Base64-encoded public key"
            ),
        ),
        migrations.AlterField(
            model_name="userpasskey",
            name="aaguid",
            field=apps.core.encryption.EncryptedCharField(
                blank=True,
                help_text="Authenticator AAGUID",
                max_length=36,
            ),
        ),
        migrations.RunPython(_reencrypt_accounts_data, migrations.RunPython.noop),
    ]
