# Generated by Codex on 2026-03-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_soft_delete_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPasskey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-defined name for this passkey", max_length=100
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        help_text="Base64-encoded credential ID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "public_key",
                    models.TextField(help_text="Base64-encoded public key"),
                ),
                (
                    "sign_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Signature counter for credential"
                    ),
                ),
                (
                    "backup_eligible",
                    models.BooleanField(
                        default=False, help_text="Whether credential is backup-eligible"
                    ),
                ),
                (
                    "backup_state",
                    models.BooleanField(
                        default=False, help_text="Current backup state of credential"
                    ),
                ),
                (
                    "aaguid",
                    models.CharField(
                        blank=True,
                        help_text="Authenticator AAGUID",
                        max_length=36,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Passkey",
                "verbose_name_plural": "User Passkeys",
                "ordering": ["-created_at"],
            },
        ),
    ]
