# Generated by Django 4.2.29 on 2026-03-25 13:41

import apps.core.encryption
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_encrypt_sensitive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=apps.core.encryption.EncryptedCharField(blank=True, encryption_context='accounts.profile.address', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=apps.core.encryption.EncryptedTextField(blank=True, encryption_context='accounts.profile.bio', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=apps.core.encryption.EncryptedCharField(blank=True, encryption_context='accounts.profile.city', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=apps.core.encryption.EncryptedCharField(blank=True, encryption_context='accounts.profile.country', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=apps.core.encryption.EncryptedDateField(blank=True, encryption_context='accounts.profile.date_of_birth', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=apps.core.encryption.EncryptedCharField(blank=True, encryption_context='accounts.profile.facebook', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=apps.core.encryption.EncryptedCharField(blank=True, encryption_context='accounts.profile.linkedin', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=apps.core.encryption.EncryptedCharField(blank=True, encryption_context='accounts.profile.twitter', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=apps.core.encryption.EncryptedTextField(blank=True, encryption_context='accounts.user.bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=apps.core.encryption.EncryptedDateField(blank=True, encryption_context='accounts.user.date_of_birth', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=apps.core.encryption.EncryptedCharField(blank=True, encryption_context='accounts.user.phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=apps.core.encryption.EncryptedCharField(blank=True, encryption_context='accounts.user.phone_number', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor'), ('DEPARTMENT_HEAD', 'Department Head'), ('SUPPORT_STAFF', 'Support Staff'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=apps.core.encryption.EncryptedCharField(blank=True, encryption_context='accounts.user.student_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='suspension_reason',
            field=apps.core.encryption.EncryptedTextField(blank=True, encryption_context='accounts.user.suspension_reason'),
        ),
        migrations.AlterField(
            model_name='userpasskey',
            name='aaguid',
            field=apps.core.encryption.EncryptedCharField(blank=True, encryption_context='accounts.userpasskey.aaguid', help_text='Authenticator AAGUID', max_length=36),
        ),
        migrations.AlterField(
            model_name='userpasskey',
            name='public_key',
            field=apps.core.encryption.EncryptedTextField(encryption_context='accounts.userpasskey.public_key', help_text='Base64-encoded public key'),
        ),
        migrations.CreateModel(
            name='MagicLinkTokenHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_link_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magic Link Token History',
                'verbose_name_plural': 'Magic Link Token Histories',
                'ordering': ['-used_at'],
            },
        ),
    ]
