# Generated by Django 4.2.29 on 2026-03-26 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0008_resource_deleted_at_resource_is_deleted_and_more'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('total_study_days', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Study streaks',
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_study_time_minutes', models.IntegerField(default=0)),
                ('sessions_count', models.IntegerField(default=0)),
                ('average_session_duration', models.FloatField(default=0.0)),
                ('resources_completed', models.IntegerField(default=0)),
                ('courses_enrolled', models.IntegerField(default=0)),
                ('courses_completed', models.IntegerField(default=0)),
                ('average_quiz_score', models.FloatField(blank=True, null=True)),
                ('average_mastery_level', models.FloatField(default=0.0)),
                ('login_frequency', models.IntegerField(default=0)),
                ('active_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('user', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('session_type', models.CharField(choices=[('study', 'Study Session'), ('reading', 'Reading'), ('video', 'Video Watching'), ('practice', 'Practice'), ('quiz', 'Quiz'), ('review', 'Review')], max_length=50)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('pages_viewed', models.IntegerField(default=0)),
                ('interactions', models.IntegerField(default=0)),
                ('focus_score', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_sessions', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='learning_an_user_id_263ef4_idx'), models.Index(fields=['subject'], name='learning_an_subject_695e7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mastery_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mastered', 'Mastered')], default='beginner', max_length=20)),
                ('quiz_score', models.FloatField(blank=True, null=True)),
                ('attempts_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='courses.course')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['user', 'completed_at'], name='learning_an_user_id_39c526_idx')],
                'unique_together': {('user', 'course', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='LearningInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('strength', 'Strength'), ('weakness', 'Weakness'), ('recommendation', 'Recommendation'), ('achievement', 'Achievement'), ('suggestion', 'Study Suggestion')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_actioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_analytics_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='learning_an_user_id_2d7463_idx')],
            },
        ),
    ]
