# Generated by Django 4.2.29 on 2026-03-25 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("gamification", "0002_alter_userpoints_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("course_completion", "Course Completion"),
                            ("achievement", "Achievement"),
                            ("milestone", "Milestone"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_verification", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Certificate Type",
                "verbose_name_plural": "Certificate Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("header_image", models.ImageField(blank=True, upload_to="certificates/templates/")),
                ("footer_text", models.CharField(blank=True, max_length=500)),
                ("background_color", models.CharField(default="#FFFFFF", max_length=20)),
                ("border_color", models.CharField(default="#000000", max_length=20)),
                ("text_color", models.CharField(default="#000000", max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "certificate_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="certificates.certificatetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Template",
                "verbose_name_plural": "Certificate Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("unique_id", models.CharField(editable=False, max_length=50, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("recipient_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("issuing_authority", models.CharField(default="CampusHub", max_length=255)),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("issued", "Issued"), ("revoked", "Revoked"), ("expired", "Expired")],
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("verification_url", models.URLField(blank=True, max_length=500)),
                ("qr_code", models.ImageField(blank=True, upload_to="certificates/qr/")),
                ("pdf_file", models.FileField(blank=True, upload_to="certificates/pdfs/")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="gamification.achievement",
                    ),
                ),
                (
                    "certificate_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="certificates.certificatetype",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="courses.course",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="certificates.certificatetemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "ordering": ["-issue_date"],
                "indexes": [
                    models.Index(fields=["user", "-issue_date"], name="certificat_user_id_d82dc8_idx"),
                    models.Index(fields=["status", "-issue_date"], name="certificat_status_e8f8f3_idx"),
                    models.Index(fields=["unique_id"], name="certificat_unique__e4a93f_idx"),
                ],
            },
        ),
    ]
