# Generated by Django 4.2.29 on 2026-03-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='certificate',
            new_name='certificate_user_id_a35f41_idx',
            old_name='certificat_user_id_d82dc8_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='certificate_status_4f224f_idx',
            old_name='certificat_status_e8f8f3_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='certificate_unique__4a27ae_idx',
            old_name='certificat_unique__e4a93f_idx',
        ),
    ]
