# Generated by Django 4.2.29 on 2026-03-08 10:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("faculties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#3b82f6", max_length=20)),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="resources.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Folder",
                "verbose_name_plural": "Folders",
                "ordering": ["-is_pinned", "name"],
            },
        ),
        migrations.CreateModel(
            name="PersonalFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#3b82f6", "Blue"),
                            ("#10b981", "Green"),
                            ("#f59e0b", "Amber"),
                            ("#ef4444", "Red"),
                            ("#8b5cf6", "Purple"),
                            ("#ec4899", "Pink"),
                            ("#06b6d4", "Cyan"),
                            ("#6b7280", "Gray"),
                        ],
                        default="#3b82f6",
                        max_length=20,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="resources.personalfolder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Folder",
                "verbose_name_plural": "Personal Folders",
                "ordering": ["-is_favorite", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("notes", "Notes"),
                            ("past_paper", "Past Paper"),
                            ("assignment", "Assignment"),
                            ("book", "Book"),
                            ("slides", "Slides"),
                            ("tutorial", "Tutorial"),
                            ("other", "Other"),
                        ],
                        default="notes",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="resources/%Y/%m/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
                ),
                ("file_size", models.BigIntegerField(default=0)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("normalized_filename", models.CharField(blank=True, max_length=255)),
                ("semester", models.CharField(blank=True, max_length=1)),
                (
                    "year_of_study",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "ocr_text",
                    models.TextField(blank=True, help_text="Extracted text from OCR"),
                ),
                (
                    "ai_summary",
                    models.TextField(blank=True, help_text="AI-generated summary"),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="courses.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="faculties.department",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="faculties.faculty",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="courses.unit",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStorage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("used_storage", models.BigIntegerField(default=0)),
                ("storage_limit", models.BigIntegerField(default=5368709120)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Storage",
                "verbose_name_plural": "User Storages",
            },
        ),
        migrations.CreateModel(
            name="ResourceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="resources/%Y/%m/additional/")),
                ("filename", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(default=0)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_files",
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource File",
                "verbose_name_plural": "Resource Files",
                "ordering": ["filename"],
            },
        ),
        migrations.CreateModel(
            name="PersonalResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("file", models.FileField(upload_to="personal/%Y/%m/")),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("file_size", models.BigIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=500)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("shared_link", "Shared via Link"),
                            ("submitted", "Submitted for Publication"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("saved", "Saved from Public"),
                            ("imported", "Imported"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_resources",
                        to="resources.personalfolder",
                    ),
                ),
                (
                    "linked_public_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_copies",
                        to="resources.resource",
                    ),
                ),
                (
                    "original_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trashed_resources",
                        to="resources.personalfolder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Resource",
                "verbose_name_plural": "Personal Resources",
                "ordering": ["-last_accessed_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FolderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="resources.folder",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folder_items",
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Folder Item",
                "verbose_name_plural": "Folder Items",
            },
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["status", "-created_at"], name="resources_r_status_223b36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["resource_type", "status"],
                name="resources_r_resourc_e067d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["uploaded_by", "status"], name="resources_r_uploade_86327d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["is_pinned", "-created_at"],
                name="resources_r_is_pinn_4a5b76_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="personalfolder",
            unique_together={("user", "name", "parent")},
        ),
        migrations.AlterUniqueTogether(
            name="folderitem",
            unique_together={("folder", "resource")},
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("user", "name", "parent")},
        ),
    ]
