# Generated by Django 4.2.29 on 2026-03-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="share_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ResourceShareEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "share_method",
                    models.CharField(
                        choices=[
                            ("copy_link", "Copy Link"),
                            ("native_share", "Native Share"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("email", "Email"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("device_info", models.CharField(blank=True, max_length=500)),
                ("shared_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_events",
                        to="resources.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_share_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Share Event",
                "verbose_name_plural": "Resource Share Events",
                "ordering": ["-shared_at"],
            },
        ),
        migrations.AddIndex(
            model_name="resourceshareevent",
            index=models.Index(
                fields=["resource", "-shared_at"], name="resources_r_resourc_aced46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceshareevent",
            index=models.Index(
                fields=["share_method", "-shared_at"],
                name="resources_r_share_m_2f5e10_idx",
            ),
        ),
    ]
