# Generated by Django 4.2.29 on 2026-03-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resourceversion_resourcerequest_courseprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceshareevent',
            name='share_method',
            field=models.CharField(choices=[('copy_link', 'Copy Link'), ('native_share', 'Native Share'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email'), ('send_to_student', 'Send to Student'), ('share_to_group', 'Share to Study Group'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
