# Generated by ChatGPT on 2026-03-13

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_alter_resourceshareevent_share_method"),
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageUpgradeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan", models.CharField(max_length=20, choices=[("starter", "Starter"), ("pro", "Pro"), ("plus", "Plus")])),
                (
                    "billing_cycle",
                    models.CharField(
                        max_length=10,
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                    ),
                ),
                ("payment_method", models.CharField(max_length=30, blank=True)),
                (
                    "status",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_upgrade_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Upgrade Request",
                "verbose_name_plural": "Storage Upgrade Requests",
                "ordering": ["-created_at"],
            },
        )
    ]
