# Generated by Codex on 2026-03-25

import apps.core.encryption
from django.db import migrations


def _reencrypt_course_progress_notes(apps, schema_editor):
    CourseProgress = apps.get_model("resources", "CourseProgress")

    for progress in CourseProgress.objects.all().iterator(chunk_size=100):
        progress.notes = progress.notes
        progress.save(update_fields=["notes"])


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0006_storage_upgrade_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseprogress",
            name="notes",
            field=apps.core.encryption.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(_reencrypt_course_progress_notes, migrations.RunPython.noop),
    ]
