# Generated by Django 4.2.29 on 2026-03-25 13:41

import apps.core.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_encrypt_course_progress_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='notes',
            field=apps.core.encryption.EncryptedTextField(blank=True, encryption_context='resources.courseprogress.notes'),
        ),
    ]
