# Generated by Django 4.2.29 on 2026-03-07 07:49

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("search_document", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("indexed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_index",
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Index",
                "verbose_name_plural": "Search Index",
                "indexes": [
                    models.Index(
                        fields=["is_active", "-indexed_at"],
                        name="search_sear_is_acti_02d959_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecentSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(max_length=255)),
                ("normalized_query", models.CharField(db_index=True, max_length=255)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("results_count", models.PositiveIntegerField(default=0)),
                (
                    "last_searched_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recent Search",
                "verbose_name_plural": "Recent Searches",
                "ordering": ["-last_searched_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_searched_at"],
                        name="search_rece_user_id_2bf0d6_idx",
                    ),
                    models.Index(
                        fields=["normalized_query", "-last_searched_at"],
                        name="search_rece_normali_cfb7e1_idx",
                    ),
                ],
                "unique_together": {("user", "normalized_query")},
            },
        ),
    ]
