# Generated by Django 4.2.29 on 2026-03-08 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_login", "User Login"),
                            ("user_logout", "User Logout"),
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_deleted", "User Deleted"),
                            ("user_activated", "User Activated"),
                            ("user_deactivated", "User Deactivated"),
                            ("password_changed", "Password Changed"),
                            ("password_reset", "Password Reset"),
                            ("resource_created", "Resource Created"),
                            ("resource_updated", "Resource Updated"),
                            ("resource_deleted", "Resource Deleted"),
                            ("resource_approved", "Resource Approved"),
                            ("resource_rejected", "Resource Rejected"),
                            ("resource_downloaded", "Resource Downloaded"),
                            ("resource_viewed", "Resource Viewed"),
                            ("faculty_created", "Faculty Created"),
                            ("faculty_updated", "Faculty Updated"),
                            ("faculty_deleted", "Faculty Deleted"),
                            ("department_created", "Department Created"),
                            ("department_updated", "Department Updated"),
                            ("department_deleted", "Department Deleted"),
                            ("course_created", "Course Created"),
                            ("course_updated", "Course Updated"),
                            ("course_deleted", "Course Deleted"),
                            ("unit_created", "Unit Created"),
                            ("unit_updated", "Unit Updated"),
                            ("unit_deleted", "Unit Deleted"),
                            ("report_created", "Report Created"),
                            ("report_resolved", "Report Resolved"),
                            ("report_dismissed", "Report Dismissed"),
                            ("announcement_created", "Announcement Created"),
                            ("announcement_updated", "Announcement Updated"),
                            ("announcement_deleted", "Announcement Deleted"),
                            ("announcement_published", "Announcement Published"),
                            ("settings_updated", "Settings Updated"),
                            ("backup_created", "Backup Created"),
                            ("cache_cleared", "Cache Cleared"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("target_type", models.CharField(blank=True, max_length=100)),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action"], name="core_auditl_action_d9fb24_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_auditl_user_id_413764_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="core_auditl_target__6c66b3_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_auditl_created_dc23ea_idx"
                    ),
                ],
            },
        ),
    ]
