# Generated by Django 4.2.29 on 2026-03-08 11:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("uploads", "Uploads"),
                            ("downloads", "Downloads"),
                            ("engagement", "Engagement"),
                            ("social", "Social"),
                            ("learning", "Learning"),
                            ("special", "Special"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points_required", models.IntegerField(default=0)),
                ("requirement_type", models.CharField(max_length=50)),
                ("requirement_value", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "points_required"],
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("total_uploads", models.IntegerField(default=0)),
                ("total_downloads", models.IntegerField(default=0)),
                ("total_ratings", models.IntegerField(default=0)),
                ("total_comments", models.IntegerField(default=0)),
                ("total_shares", models.IntegerField(default=0)),
                ("consecutive_login_days", models.IntegerField(default=0)),
                ("last_login_date", models.DateField(blank=True, null=True)),
                ("resources_shared", models.IntegerField(default=0)),
                ("resources_saved", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamification_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Stats",
                "verbose_name_plural": "User Stats",
            },
        ),
        migrations.CreateModel(
            name="UserPoints",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload_resource", "Upload Resource"),
                            ("download_resource", "Download Resource"),
                            ("rate_resource", "Rate Resource"),
                            ("comment_resource", "Comment Resource"),
                            ("complete_profile", "Complete Profile"),
                            ("daily_login", "Daily Login"),
                            ("share_resource", "Share Resource"),
                            ("report_content", "Report Content"),
                            ("verify_email", "Verify Email"),
                            ("first_upload", "First Upload"),
                            ("first_download", "First Download"),
                            ("referral", "Referral"),
                        ],
                        max_length=30,
                    ),
                ),
                ("points", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Points",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("points_earned", models.IntegerField(default=0)),
                ("milestone_type", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by",
                        to="gamification.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge")},
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("all_time", "All Time"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rank", models.IntegerField()),
                ("points", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_rankings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["period", "rank"],
                "unique_together": {("period", "user")},
            },
        ),
    ]
