# Generated by Django 4.2.29 on 2026-03-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpoints",
            name="action",
            field=models.CharField(
                choices=[
                    ("upload_resource", "Upload Resource"),
                    ("download_resource", "Download Resource"),
                    ("rate_resource", "Rate Resource"),
                    ("comment_resource", "Comment Resource"),
                    ("complete_profile", "Complete Profile"),
                    ("daily_login", "Daily Login"),
                    ("share_resource", "Share Resource"),
                    ("report_content", "Report Content"),
                    ("verify_email", "Verify Email"),
                    ("first_upload", "First Upload"),
                    ("first_download", "First Download"),
                    ("referral", "Referral"),
                    ("earn_badge", "Earn Badge"),
                ],
                max_length=30,
            ),
        ),
    ]
