# Generated by Django 4.2.29 on 2026-03-25 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify
import uuid


def populate_unique_achievement_slugs(apps, schema_editor):
    Achievement = apps.get_model("gamification", "Achievement")
    seen = set()

    for achievement in Achievement.objects.all().order_by("id"):
        base_source = achievement.slug or achievement.title or achievement.name or f"achievement-{achievement.id}"
        base_slug = slugify(base_source) or f"achievement-{achievement.id}"
        candidate = base_slug
        index = 1
        while candidate in seen:
            index += 1
            candidate = f"{base_slug}-{index}"
        seen.add(candidate)
        achievement.slug = candidate
        achievement.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0002_alter_userpoints_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('learning', 'Learning'), ('social', 'Social'), ('engagement', 'Engagement'), ('special', 'Special')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achievement Category',
                'verbose_name_plural': 'Achievement Categories',
                'db_table': 'gamification_achievement_categories',
            },
        ),
        migrations.CreateModel(
            name='AchievementTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], max_length=20, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Point multiplier for this tier', max_digits=3)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Achievement Tier',
                'verbose_name_plural': 'Achievement Tiers',
                'db_table': 'gamification_achievement_tiers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BadgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('uploads', 'Uploads'), ('downloads', 'Downloads'), ('engagement', 'Engagement'), ('learning', 'Learning'), ('social', 'Social'), ('streak', 'Streak'), ('special', 'Special')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Badge Category',
                'verbose_name_plural': 'Badge Categories',
                'db_table': 'gamification_badge_categories',
            },
        ),
        migrations.CreateModel(
            name='BadgeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Point multiplier for this badge level', max_digits=3)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge Level',
                'verbose_name_plural': 'Badge Levels',
                'db_table': 'gamification_badge_levels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PointAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('points', models.IntegerField(default=0, help_text='Points awarded for this action')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_times_per_day', models.PositiveIntegerField(default=1, help_text='Maximum times this action can be performed per day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Point Action',
                'verbose_name_plural': 'Point Actions',
                'db_table': 'gamification_point_actions',
            },
        ),
        migrations.CreateModel(
            name='PointCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('learning', 'Learning'), ('engagement', 'Engagement'), ('contribution', 'Contribution'), ('achievement', 'Achievement')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or identifier', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Point Category',
                'verbose_name_plural': 'Point Categories',
                'db_table': 'gamification_point_categories',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, help_text='Reference ID for related object (e.g., task ID, study session ID)', max_length=100)),
                ('reference_type', models.CharField(blank=True, help_text="Type of reference (e.g., 'task', 'study_session', 'referral')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'db_table': 'gamification_point_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreakHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of activity')),
                ('activity_count', models.PositiveIntegerField(default=0, help_text='Number of activities on this day')),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Points earned on this day')),
                ('streak_at_date', models.PositiveIntegerField(default=0, help_text='Streak length on this date')),
                ('milestone_reached', models.CharField(blank=True, help_text='Milestone reached (7, 30, 100)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Streak History',
                'verbose_name_plural': 'Streak Histories',
                'db_table': 'gamification_streak_history',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StreakReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_milestone', models.PositiveIntegerField(choices=[(7, '7 Days'), (30, '30 Days'), (100, '100 Days')])),
                ('reward_type', models.CharField(choices=[('points', 'Points'), ('badge', 'Badge'), ('both', 'Both')], max_length=20)),
                ('bonus_points', models.PositiveIntegerField(default=0, help_text='Bonus points awarded')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Streak Reward',
                'verbose_name_plural': 'Streak Rewards',
                'db_table': 'gamification_streak_rewards',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_progress', models.PositiveIntegerField(default=0, help_text='Current progress value')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date when achievement was completed', null=True)),
                ('is_reward_claimed', models.BooleanField(default=False, help_text='Whether reward has been claimed')),
                ('claimed_at', models.DateTimeField(blank=True, help_text='Date when reward was claimed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'db_table': 'gamification_user_achievements',
                'ordering': ['-completed_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current consecutive days streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='Longest streak ever achieved')),
                ('last_activity_date', models.DateField(blank=True, help_text='Date of last recorded activity', null=True)),
                ('streak_freezes', models.PositiveIntegerField(default=1, help_text='Number of streak freezes available (max 1)')),
                ('is_frozen', models.BooleanField(default=False, help_text='Whether streak is currently frozen')),
                ('freeze_start_date', models.DateField(blank=True, help_text='Date when streak was frozen', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Streak',
                'verbose_name_plural': 'User Streaks',
                'db_table': 'gamification_user_streaks',
            },
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['tier', 'category', 'order', 'name'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['level', 'category', 'name'], 'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['period', 'rank', '-created_at'], 'verbose_name': 'Leaderboard', 'verbose_name_plural': 'Leaderboards'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-earned_at'], 'verbose_name': 'User Badge', 'verbose_name_plural': 'User Badges'},
        ),
        migrations.AlterModelOptions(
            name='userpoints',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Points', 'verbose_name_plural': 'User Points'},
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='achievement',
            name='badge',
            field=models.ForeignKey(blank=True, help_text='Badge awarded on completion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='gamification.badge'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured on achievement page'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='Untitled Achievement', max_length=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='points_reward',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded on completion'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='premium_days_reward',
            field=models.PositiveIntegerField(default=0, help_text='Premium days awarded on completion'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='profile_customization',
            field=models.CharField(blank=True, help_text='Profile customization unlocked on completion', max_length=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='target_type',
            field=models.CharField(default='default', help_text='Type of target: courses_completed, study_hours, posts_count, streak_days, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='achievement',
            name='target_value',
            field=models.PositiveIntegerField(default=1, help_text='Target value to complete the achievement'),
        ),
        migrations.AddField(
            model_name='badge',
            name='action_count_required',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the action must be performed'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='department_id',
            field=models.PositiveIntegerField(blank=True, help_text='Department ID for department leaderboards', null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='faculty_id',
            field=models.PositiveIntegerField(blank=True, help_text='Faculty ID for faculty leaderboards', null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='leaderboard_type',
            field=models.CharField(choices=[('global', 'Global'), ('faculty', 'Faculty'), ('department', 'Department')], default='global', max_length=20),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='snapshot_data',
            field=models.JSONField(default=dict, help_text='JSON containing ranked user data'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='achievement_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='contribution_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='engagement_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='learning_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='milestone_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievement_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='badge',
            name='points_required',
            field=models.PositiveIntegerField(default=0, help_text='Total points required to earn this badge'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='requirement_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], default='weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_rankings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='gamification.badge'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='action',
            field=models.CharField(choices=[('__summary__', 'Summary'), ('upload_resource', 'Upload Resource'), ('download_resource', 'Download Resource'), ('rate_resource', 'Rate Resource'), ('comment_resource', 'Comment Resource'), ('daily_login', 'Daily Login'), ('share_resource', 'Share Resource'), ('verify_email', 'Verify Email'), ('earn_badge', 'Earn Badge'), ('other', 'Other')], default='__summary__', max_length=30),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_unique_achievement_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['leaderboard_type', 'period', '-created_at'], name='gamificatio_leaderb_9c2283_idx'),
        ),
        migrations.AddIndex(
            model_name='userpoints',
            index=models.Index(fields=['user', 'action', '-created_at'], name='gamificatio_user_id_79f25c_idx'),
        ),
        migrations.AlterModelTable(
            name='achievement',
            table='gamification_achievements',
        ),
        migrations.AlterModelTable(
            name='badge',
            table='gamification_badges',
        ),
        migrations.AlterModelTable(
            name='leaderboard',
            table='gamification_leaderboards',
        ),
        migrations.AlterModelTable(
            name='userbadge',
            table='gamification_user_badges',
        ),
        migrations.AlterModelTable(
            name='userpoints',
            table='gamification_user_points',
        ),
        migrations.AlterModelTable(
            name='userstats',
            table='gamification_user_stats',
        ),
        migrations.AddField(
            model_name='userstreak',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='gamification.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streakreward',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streak_rewards', to='gamification.badge'),
        ),
        migrations.AddField(
            model_name='streakhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gamification.pointaction'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gamification.pointcategory'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='gamification.pointcategory'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='gamification.achievementcategory'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='gamification.achievementtier'),
        ),
        migrations.AddField(
            model_name='badge',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='gamification.badgelevel'),
        ),
        migrations.AddField(
            model_name='badge',
            name='related_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='gamification.pointaction'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='gamification.badgecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AlterUniqueTogether(
            name='streakreward',
            unique_together={('streak_milestone',)},
        ),
        migrations.AddIndex(
            model_name='streakhistory',
            index=models.Index(fields=['user', '-date'], name='gamificatio_user_id_79819b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='streakhistory',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_3af827_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['reference_id', 'reference_type'], name='gamificatio_referen_951662_idx'),
        ),
    ]
