# Generated by Django 4.2.29 on 2026-03-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_achievementcategory_achievementtier_badgecategory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together={('slug',)},
        ),
    ]
