# Generated by Django 4.2.29 on 2026-03-08 10:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged"),
                            ("removed", "Removed"),
                            ("locked", "Locked"),
                            ("unlocked", "Unlocked"),
                            ("hidden", "Hidden"),
                            ("restored", "Restored"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="comments.comment",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="resources.resource",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation Log",
                "verbose_name_plural": "Moderation Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="moderationlog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("resource__isnull", False),
                    ("comment__isnull", False),
                    _connector="OR",
                ),
                name="moderation_log_has_target",
            ),
        ),
    ]
