# Generated by Django 4.2.29 on 2026-03-09 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('resource_approved', 'Resource Approved'), ('resource_rejected', 'Resource Rejected'), ('resource_flagged', 'Resource Flagged'), ('resource_archived', 'Resource Archived'), ('resource_deleted', 'Resource Deleted'), ('resource_restored', 'Resource Restored'), ('report_resolved', 'Report Resolved'), ('report_dismissed', 'Report Dismissed'), ('user_suspended', 'User Suspended'), ('user_activated', 'User Activated'), ('user_role_updated', 'User Role Updated'), ('announcement_published', 'Announcement Published'), ('announcement_archived', 'Announcement Archived'), ('faculty_created', 'Faculty Created'), ('faculty_updated', 'Faculty Updated'), ('department_created', 'Department Created'), ('department_updated', 'Department Updated'), ('course_created', 'Course Created'), ('course_updated', 'Course Updated'), ('unit_created', 'Unit Created'), ('unit_updated', 'Unit Updated')], max_length=50)),
                ('target_type', models.CharField(choices=[('resource', 'Resource'), ('report', 'Report'), ('user', 'User'), ('announcement', 'Announcement'), ('faculty', 'Faculty'), ('department', 'Department'), ('course', 'Course'), ('unit', 'Unit'), ('system', 'System')], max_length=20)),
                ('target_id', models.CharField(max_length=50)),
                ('target_title', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='moderationlog',
            name='moderation_log_has_target',
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('removed', 'Removed'), ('locked', 'Locked'), ('unlocked', 'Unlocked'), ('hidden', 'Hidden'), ('restored', 'Restored'), ('archived', 'Archived')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='moderationlog',
            constraint=models.CheckConstraint(check=models.Q(('resource__isnull', False), ('comment__isnull', False), ('user__isnull', False), _connector='OR'), name='moderation_log_has_target'),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['-created_at'], name='moderation__created_6500af_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['admin', '-created_at'], name='moderation__admin_i_7de3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['action', '-created_at'], name='moderation__action_85f64c_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['target_type', 'target_id'], name='moderation__target__1c3d61_idx'),
        ),
    ]
