# Generated by Django 4.2.29 on 2026-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_adminactivitylog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('resource_approved', 'Resource Approved'), ('resource_rejected', 'Resource Rejected'), ('resource_flagged', 'Resource Flagged'), ('resource_archived', 'Resource Archived'), ('resource_deleted', 'Resource Deleted'), ('resource_restored', 'Resource Restored'), ('report_resolved', 'Report Resolved'), ('report_dismissed', 'Report Dismissed'), ('user_suspended', 'User Suspended'), ('user_activated', 'User Activated'), ('user_role_updated', 'User Role Updated'), ('user_invitation_created', 'User Invitation Created'), ('user_invitation_sent', 'User Invitation Sent'), ('user_invitation_batch_created', 'User Invitation Batch Created'), ('user_invitation_revoked', 'User Invitation Revoked'), ('user_invitation_accepted', 'User Invitation Accepted'), ('announcement_published', 'Announcement Published'), ('announcement_archived', 'Announcement Archived'), ('faculty_created', 'Faculty Created'), ('faculty_updated', 'Faculty Updated'), ('department_created', 'Department Created'), ('department_updated', 'Department Updated'), ('course_created', 'Course Created'), ('course_updated', 'Course Updated'), ('unit_created', 'Unit Created'), ('unit_updated', 'Unit Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='target_type',
            field=models.CharField(choices=[('resource', 'Resource'), ('report', 'Report'), ('user', 'User'), ('announcement', 'Announcement'), ('faculty', 'Faculty'), ('department', 'Department'), ('course', 'Course'), ('unit', 'Unit'), ('system', 'System'), ('role_invitation', 'Role Invitation'), ('role_invitation_batch', 'Role Invitation Batch')], max_length=30),
        ),
    ]
