# Generated by Django 4.2.29 on 2026-03-26 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftTeamsAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('microsoft_user_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('sync_status', models.CharField(choices=[('active', 'Active'), ('syncing', 'Syncing'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_teams_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Microsoft Teams Account',
                'verbose_name_plural': 'Microsoft Teams Accounts',
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('manual', 'Manual Sync')], max_length=20)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('teams_count', models.PositiveIntegerField(default=0)),
                ('channels_count', models.PositiveIntegerField(default=0)),
                ('assignments_count', models.PositiveIntegerField(default=0)),
                ('announcements_count', models.PositiveIntegerField(default=0)),
                ('submissions_count', models.PositiveIntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_history', to='microsoft_teams.microsoftteamsaccount')),
            ],
            options={
                'verbose_name': 'Sync State',
                'verbose_name_plural': 'Sync States',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncedTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(blank=True, max_length=50)),
                ('owner_id', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_teams', to='microsoft_teams.microsoftteamsaccount')),
                ('linked_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='microsoft_teams_links', to='courses.unit')),
            ],
            options={
                'verbose_name': 'Synced Team',
                'verbose_name_plural': 'Synced Teams',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='SyncedChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_general', models.BooleanField(default=False)),
                ('web_url', models.URLField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('synced_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_channels', to='microsoft_teams.syncedteam')),
            ],
            options={
                'verbose_name': 'Synced Channel',
                'verbose_name_plural': 'Synced Channels',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='SyncedAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('due_date_time', models.DateTimeField(blank=True, null=True)),
                ('due_date_includes_time', models.BooleanField(default=True)),
                ('grading_type', models.CharField(blank=True, max_length=50)),
                ('max_points', models.FloatField(blank=True, null=True)),
                ('web_url', models.URLField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('synced_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_assignments', to='microsoft_teams.syncedteam')),
            ],
            options={
                'verbose_name': 'Synced Assignment',
                'verbose_name_plural': 'Synced Assignments',
                'ordering': ['-due_date_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncedAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement_id', models.CharField(max_length=255, unique=True)),
                ('topic', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('web_url', models.URLField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('synced_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_announcements', to='microsoft_teams.syncedchannel')),
            ],
            options={
                'verbose_name': 'Synced Announcement',
                'verbose_name_plural': 'Synced Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncedSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_id', models.CharField(max_length=255, unique=True)),
                ('student_email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('not_started', 'Not Started'), ('working_on_it', 'Working On It'), ('submitted', 'Submitted'), ('returned', 'Returned')], default='not_started', max_length=30)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('synced_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_submissions', to='microsoft_teams.syncedassignment')),
            ],
            options={
                'verbose_name': 'Synced Submission',
                'verbose_name_plural': 'Synced Submissions',
                'unique_together': {('synced_assignment', 'student_email')},
            },
        ),
    ]
