# Generated by Codex on 2026-03-25

import apps.core.encryption
from django.db import migrations


SETTING_FIELDS = ["totp_secret", "backup_codes"]
VERIFICATION_FIELDS = ["code"]


def _reencrypt_two_factor_data(apps, schema_editor):
    TwoFactorSetting = apps.get_model("two_factor", "TwoFactorSetting")
    TwoFactorVerification = apps.get_model("two_factor", "TwoFactorVerification")

    for record in TwoFactorSetting.objects.all().iterator(chunk_size=100):
        for field_name in SETTING_FIELDS:
            setattr(record, field_name, getattr(record, field_name))
        record.save(update_fields=SETTING_FIELDS)

    for record in TwoFactorVerification.objects.all().iterator(chunk_size=100):
        for field_name in VERIFICATION_FIELDS:
            setattr(record, field_name, getattr(record, field_name))
        record.save(update_fields=VERIFICATION_FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("two_factor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twofactorsetting",
            name="totp_secret",
            field=apps.core.encryption.EncryptedCharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="twofactorsetting",
            name="backup_codes",
            field=apps.core.encryption.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="twofactorverification",
            name="code",
            field=apps.core.encryption.EncryptedCharField(max_length=32),
        ),
        migrations.RunPython(_reencrypt_two_factor_data, migrations.RunPython.noop),
    ]
