# Generated by Django 4.2.29 on 2026-03-25 13:41

import apps.core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor', '0002_encrypt_sensitive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorsetting',
            name='backup_codes',
            field=apps.core.encryption.EncryptedJSONField(blank=True, default=list, encryption_context='two_factor.twofactorsetting.backup_codes'),
        ),
        migrations.AlterField(
            model_name='twofactorsetting',
            name='totp_secret',
            field=apps.core.encryption.EncryptedCharField(blank=True, encryption_context='two_factor.twofactorsetting.totp_secret', max_length=128),
        ),
        migrations.AlterField(
            model_name='twofactorverification',
            name='code',
            field=apps.core.encryption.EncryptedCharField(encryption_context='two_factor.twofactorverification.code', max_length=32),
        ),
    ]
