# Generated by Django 4.2.29 on 2026-03-07 07:49

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInterestProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("favorite_tags", models.JSONField(blank=True, default=list)),
                ("favorite_units", models.JSONField(blank=True, default=list)),
                ("favorite_resource_types", models.JSONField(blank=True, default=list)),
                ("behavior_summary", models.JSONField(blank=True, default=dict)),
                ("embedding_vector_key", models.CharField(blank=True, max_length=255)),
                (
                    "last_computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Interest Profile",
                "verbose_name_plural": "User Interest Profiles",
            },
        ),
        migrations.CreateModel(
            name="RecommendationCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("for_you", "For You"),
                            ("trending", "Trending"),
                            ("course_based", "Course Based"),
                            ("related", "Related"),
                            ("download_based", "Download Based"),
                            ("saved_based", "Saved Based"),
                        ],
                        max_length=30,
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("rank", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_cache_rows",
                        to="resources.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_cache",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation Cache",
                "verbose_name_plural": "Recommendation Cache",
                "ordering": ["category", "rank"],
                "indexes": [
                    models.Index(
                        fields=["user", "category", "expires_at"],
                        name="recommendat_user_id_12fc99_idx",
                    ),
                    models.Index(
                        fields=["resource", "category"],
                        name="recommendat_resourc_83b95a_idx",
                    ),
                ],
                "unique_together": {("user", "resource", "category")},
            },
        ),
    ]
