# Generated by Django 4.2.29 on 2026-03-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inapppurchase',
            new_name='payments_in_user_id_1e1371_idx',
            old_name='payments_ina_user_1f98c0_idx',
        ),
        migrations.RenameIndex(
            model_name='inapppurchase',
            new_name='payments_in_platfor_d8a9c6_idx',
            old_name='payments_ina_platfor_77b97b_idx',
        ),
        migrations.RenameIndex(
            model_name='inapppurchase',
            new_name='payments_in_platfor_114e31_idx',
            old_name='payments_ina_platfor_f307b8_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_user_id_01767a_idx',
            old_name='payments_pay_user_5e56ef_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_stripe__6fe52c_idx',
            old_name='payments_pay_stripe__94e16c_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='payments_su_user_id_058311_idx',
            old_name='payments_sub_user_2756ce_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='payments_su_stripe__6d2a04_idx',
            old_name='payments_sub_stripe__6e89eb_idx',
        ),
    ]
