# Generated by Django 4.2.29 on 2026-03-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_payments_ina_user_1f98c0_idx_payments_in_user_id_1e1371_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='badge_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='plan',
            name='bookmark_limit',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='event_limit_monthly',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='group_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='message_limit_daily',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='notification_delay_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='points_limit_monthly',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='plan',
            name='search_results_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='support_response_hours',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='plan',
            name='upload_limit_monthly',
            field=models.IntegerField(default=10),
        ),
    ]
