# Generated by Django 4.2.29 on 2026-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0002_role_invitation_upgrade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admininvitationbatch',
            new_name='admin_invit_created_e5b1a6_idx',
            old_name='admin_invit_created_7b4ce3_idx',
        ),
        migrations.RenameIndex(
            model_name='admininvitationrole',
            new_name='admin_invit_code_65bbb0_idx',
            old_name='admin_invit_code_5ae11f_idx',
        ),
        migrations.RenameIndex(
            model_name='admininvitationrole',
            new_name='admin_invit_is_acti_a63ccf_idx',
            old_name='admin_invit_is_act_4370c3_idx',
        ),
        migrations.RenameIndex(
            model_name='adminroleinvitation',
            new_name='admin_role__email_d6aca2_idx',
            old_name='admin_role__email_50d905_idx',
        ),
        migrations.RenameIndex(
            model_name='adminroleinvitation',
            new_name='admin_role__role_e3729b_idx',
            old_name='admin_role__role_2a9013_idx',
        ),
        migrations.RenameIndex(
            model_name='adminroleinvitation',
            new_name='admin_role__expires_d7bb4d_idx',
            old_name='admin_role__expire_ee40be_idx',
        ),
        migrations.RenameIndex(
            model_name='adminroleinvitation',
            new_name='admin_role__source_f9a818_idx',
            old_name='admin_role__source_36245f_idx',
        ),
        migrations.RenameIndex(
            model_name='adminuserroleassignment',
            new_name='admin_user__user_id_062bc8_idx',
            old_name='admin_user__user_id_0bdb0f_idx',
        ),
        migrations.RenameIndex(
            model_name='contentcalendarevent',
            new_name='admin_conte_start_d_675a07_idx',
            old_name='admin_conte_start_d7f14f_idx',
        ),
        migrations.RenameIndex(
            model_name='contentcalendarevent',
            new_name='admin_conte_event_t_7b1a2e_idx',
            old_name='admin_conte_event_t_6f5afd_idx',
        ),
        migrations.RenameIndex(
            model_name='contentcalendarevent',
            new_name='admin_conte_status_201336_idx',
            old_name='admin_conte_status_0708f6_idx',
        ),
        migrations.AlterField(
            model_name='adminroleinvitation',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor'), ('DEPARTMENT_HEAD', 'Department Head'), ('SUPPORT_STAFF', 'Support Staff'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
