from django.core.management.base import BaseCommand
from apps.courses.models import Course, Unit

# Curated units extracted from the provided curriculum text.
COURSE_UNITS = {
    "BCS": [
        (1, "2", "BPHY 1204", "DIGITAL LOGIC AND ELECTRONICS"),
        (1, "2", "BCSC 1204", "DATA STRUCTURES AND ALGORITHMS"),
        (1, "2", "BPHY 1205", "ELECTRONICS I"),
        (1, "2", "BSTA 1203", "PROBABILITY AND STATISTICS I"),
        (1, "2", "BMAT 1204", "DISCRETE MATHEMATICS"),
        (1, "2", "BMAT 1205", "CALCULUS I"),
        (1, "2", "BCSE 1203", "STRUCTURED PROGRAMMING LAB"),
        (1, "2", "BUCI 1104", "COMPUTER APPLICATIONS"),
        (1, "2", "BCSC 2103", "COMPUTER DESIGN AND ORGANIZATION"),
        (1, "2", "BCIT 2112", "SYSTEM ANALYSIS AND DESIGN"),
        (1, "2", "BMAT 2109", "LINEAR ALGEBRA"),
        (1, "2", "BCSC 1102", "INTRODUCTION TO PROGRAMMING"),
        (1, "2", "BUCI 1101", "COMMUNICATION SKILLS"),
        (1, "2", "BUCI 1102", "LIFE SKILLS"),
        (1, "2", "BMAT 1101", "BASIC MATHEMATICS"),
        (2, "2", "BCIT 1210", "DATABASE MANAGEMENT SYSTEMS"),
        (2, "2", "BCIT 1208", "COMPUTER NETWORKS"),
        (2, "2", "BCIT 2217", "OBJECT ORIENTED PROGRAMMING II"),
        (2, "2", "BCSC 2207", "SCIENTIFIC COMPUTING"),
        (2, "2", "BCIT 2218", "INTERNET APPLICATION PROGRAMMING"),
        (2, "2", "BCIT 2214", "SOFTWARE ENGINEERING"),
        (2, "2", "BENT 1207", "ENTREPRENEURSHIP SKILLS"),
        (3, "2", "BCSC 3220", "COMPILER CONSTRUCTION AND DESIGN"),
        (3, "2", "BCSC 3212", "QUANTUM COMPUTER SCIENCE"),
        (3, "2", "BCIT 3238", "MOBILE APPLICATION DEVELOPMENT"),
        (3, "2", "BCIT 3262", "DATABASE PROGRAMMING"),
        (3, "2", "BCIT 4261", "SYSTEM SECURITY AND AUDIT"),
        (3, "2", "BCIT 3260", "RESEARCH METHODS FOR IT"),
        (3, "2", "BCSC 3225", "ARTIFICIAL INTELLIGENCE"),
        (4, "2", "BCSC 4234", "COMPUTER GRAPHICS"),
        (4, "2", "BCIT 4266", "COMPUTING LAW AND ETHICS"),
        (4, "2", "BCIT 4264", "PROJECT II (SYSTEM DEVELOPMENT)"),
        (4, "2", "BSCS 4227", "DATA SCIENCE"),
        (4, "2", "BCSC 4232", "EXPERT SYSTEMS"),
        (4, "2", "BCSC 4248", "PATTERN RECOGNITION"),
        (4, "2", "BCSC 4250", "NETWORK PROGRAMMING"),
    ],
    "DCS": [
        (1, "2", "DCS 1.20412 551 10A", "Apply Business Maths and Statistics"),
        (1, "2", "DCS 1.20412 551 22A", "Cooperative Practices"),
        (1, "2", "DCS 1.20613 554 10A", "Apply Mathematics for Computer Science"),
        (1, "2", "DCS 1.20613 554 03A", "Networking and Distributed Systems"),
        (1, "2", "DCS 1.20613 554 04A", "Graphics Design"),
    ],
    "BIT": [
        (1, "2", "BENT 1207", "ENTREPRENEURSHIP SKILLS"),
        (1, "2", "BMAT 1205", "CALCULUS I"),
        (1, "2", "BCIT 1202", "DATA COMMUNICATION AND COMPUTER NETWORKS"),
        (1, "2", "BCIT 1210", "DATABASE MANAGEMENT SYSTEMS"),
        (1, "2", "BMAT 1204", "DISCRETE MATHEMATICS"),
        (1, "2", "CSC 1204", "DATA STRUCTURES AND ALGORITHMS"),
        (1, "2", "CSE 1203", "STRUCTURED PROGRAMMING LAB"),
        (2, "2", "BCIT 2230", "ADVANCED OPERATING SYSTEMS"),
        (2, "2", "BCSC 2205", "COMPUTER AIDED ART AND DESIGN"),
        (2, "2", "BCIT 2217", "OBJECT ORIENTED PROGRAMMING II"),
        (2, "2", "BPHY 1204", "DIGITAL LOGIC AND ELECTRONICS"),
        (2, "2", "BSTA 1203", "PROBABILITY AND STATISTICS I"),
        (2, "2", "BCIT 2214", "SOFTWARE ENGINEERING"),
        (2, "2", "BCIT 2213", "NETWORKS AND SYSTEMS ADMINISTRATION"),
        (3, "2", "BCIT 3238", "MOBILE APPLICATION DEVELOPMENT"),
        (3, "2", "BCIT 3237", "ELECTRONIC COMMERCE"),
        (3, "2", "BCIT 3242", "ADVANCED DATABASE MANAGEMENT SYSTEMS"),
        (3, "2", "BCSC 3225", "ARTIFICIAL INTELLIGENCE"),
        (3, "2", "BCIT 3260", "RESEARCH METHODS FOR IT"),
        (3, "2", "BCIT 3265", "DISTRIBUTED SYSTEMS"),
        (3, "2", "BCIT 3244", "MULTIMEDIA SYSTEMS"),
        (4, "2", "BCSC 4227", "DATA SCIENCE"),
        (4, "2", "BCIT 4255", "INFORMATION SYSTEMS AUDIT"),
        (4, "2", "BCSC 4231", "KNOWLEDGE BASED SYSTEMS"),
        (4, "2", "BCIT 4266", "COMPUTING LAW AND ETHICS"),
        (4, "2", "BCIT 4264", "PROJECT II (SYSTEM DEVELOPMENT)"),
    ],
    "BBIT": [
        (1, "2", "BCIT 1207", "INTRODUCTION TO INFORMATION SYSTEMS"),
        (1, "2", "BMGT 1201", "PRINCIPLES AND PRACTICE OF MANAGEMENT"),
        (1, "2", "BLAW 1201", "BUSINESS LAW"),
        (1, "2", "BMKT 1202", "PRINCIPLES OF MARKETING"),
        (1, "2", "BENT 1207", "ENTREPRENEURSHIP SKILLS"),
        (2, "1", "BCIT 2112", "SYSTEMS ANALYSIS AND DESIGN"),
        (2, "1", "BUCI 1101", "COMMUNICATION SKILLS"),
        (2, "1", "BCSC 1102", "INTRODUCTION TO PROGRAMMING"),
        (2, "1", "BECO 1101", "PRINCIPLES OF MICROECONOMICS"),
        (2, "1", "BSTA 2101", "STATISTICS"),
        (2, "1", "BUCI 1102", "LIFE SKILLS"),
        (2, "1", "BUCI 1105", "COOPERATIVE PHILOSOPHY"),
        (2, "1", "BCIT 1210", "DATABASE MANAGEMENT SYSTEMS"),
        (2, "1", "BCIT 2219", "MANAGEMENT INFORMATION SYSTEMS"),
        (2, "2", "BCIT 1208", "COMPUTER NETWORKS"),
        (2, "2", "BCIT 1210", "DATABASE MANAGEMENT SYSTEMS"),
        (2, "2", "BECO 1202", "PRINCIPLES OF MACROECONOMICS"),
        (2, "2", "BCIT 2219", "MANAGEMENT INFORMATION SYSTEMS"),
        (2, "2", "BMAT 1207", "MATHEMATICS II"),
        (3, "2", "BCIT 2122", "OBJECT ORIENTED PROGRAMMING"),
        (3, "2", "BCIT 3260", "RESEARCH METHODS FOR IT"),
        (3, "2", "BCIT 3237", "ELECTRONIC COMMERCE"),
        (3, "2", "BCIT 2132", "WEB DEVELOPMENT"),
        (3, "2", "BECO 1101", "PRINCIPLES OF MICROECONOMICS"),
        (3, "2", "BMAT 1102", "MATHEMATICS I"),
        (3, "2", "BUCI 1101", "COMMUNICATION SKILLS"),
        (3, "2", "BUCI 1102", "LIFE SKILLS"),
        (3, "2", "BUCI 1105", "COOPERATIVE PHILOSOPHY"),
        (4, "2", "BFIN 2225", "FINANCIAL ETHICS AND STANDARDS"),
        (4, "2", "BCIT 4254", "ICT COMMERCIALIZATION"),
        (4, "2", "BCIT 4255", "INFORMATION SYSTEMS AUDIT"),
        (4, "2", "BCIT 4264", "PROJECT II (SYSTEM DEVELOPMENT)"),
        (4, "2", "BCSC 4214", "MOBILE COMPUTING"),
        (4, "2", "BCSC 4126", "SIMULATION AND MODELLING"),
        (4, "2", "BENT 1207", "ENTREPRENEURSHIP SKILLS"),
        (4, "2", "BMGT 1201", "PRINCIPLES AND PRACTICE OF MANAGEMENT"),
    ],
    "DIT": [
        (1, "2", "DIT 1.2 0031 441 05A", "Cooperative Practices"),
        (1, "2", "DIT 1.2 0619 451 06A", "Computer Software"),
        (1, "2", "DIT 1.2 0612 451 07A", "Network Design and Management"),
        (1, "2", "DIT 1.2 0613 451 05A", "Computer Programming Principles"),
        (1, "2", "DIT 1.2 0612 451 08A", "Computerized Database System"),
        (1, "2", "DIT 1.2 0541 541 01A", "Discrete Mathematical Concepts"),
        (2, "2", "DIT 2.2 DCIT 1208", "WEB ENGINEERING (CLOUD AND MOBILE)"),
        (2, "2", "DIT 2.2 DCSC 2212", "NETWORK DESIGN AND SETUP"),
        (2, "2", "DIT 2.2 DCIT 2215", "PROJECT WORK (DOCUMENTATION AND SYSTEM IMPLEMENTATION)"),
        (2, "2", "DIT 2.2 DCSC 2207", "EVENT DRIVEN PROGRAMMING"),
        (2, "2", "DIT 2.2 DCSC 2210", "DIGITAL ELECTRONICS CONSTRUCTION"),
    ],
    "DCY": [
        (1, "2", "DCY 1.2 0612554 05A", "Install and Configure Linux"),
        (1, "2", "DCY 1.2 0612554 06A", "Secure Software Application"),
        (1, "2", "DCY 1.2 0612554 03A", "Apply Cooperative Practices"),
        (2, "2", "DCY 2.2 DICY 2218", "Security Assessment and Testing"),
        (2, "2", "DCY 2.2 DICY 2219", "Security Operations management"),
    ],
    "BSEN": [
        (1, "2", "BCSE 1203", "STRUCTURED PROGRAMMING LAB"),
        (1, "2", "BCSC 1204", "DATA STRUCTURES AND ALGORITHMS"),
        (1, "2", "BMAT 1204", "DISCRETE MATHEMATICS"),
        (1, "2", "BMAT 1205", "CALCULUS I"),
        (1, "2", "BSTA 1203", "PROBABILITY AND STATISTICS I"),
        (1, "2", "BPHY 1204", "DIGITAL LOGIC AND ELECTRONICS"),
        (2, "2", "BCIT 1210", "DATABASE MANAGEMENT SYSTEMS"),
        (2, "2", "BCSE 2206", "SOFTWARE REQUIREMENTS ENGINEERING"),
        (2, "2", "BCSE 2207", "SOFTWARE METRICS"),
        (2, "2", "BCIT 2218", "INTERNET APPLICATION PROGRAMMING"),
        (2, "2", "BCSE 2208", "FUNDAMENTALS OF OBJECT ORIENTED PROGRAMMING WITH JAVA"),
        (2, "2", "BCIT 3262", "DATABASE PROGRAMMING"),
        (2, "2", "BENT 1207", "ENTREPRENEURSHIP SKILLS"),
        (3, "2", "BCSC 3220", "COMPILER CONSTRUCTION AND DESIGN"),
        (3, "2", "BCIT 3238", "MOBILE APPLICATION DEVELOPMENT"),
        (3, "2", "BCIT 3260", "RESEARCH METHODS FOR IT"),
        (3, "2", "BCSE 3211", "SOFTWARE VERIFICATION AND VALIDATION"),
        (3, "2", "BCSE 3212", "OBJECT ORIENTED ANALYSIS AND DESIGN WITH UML"),
        (3, "2", "BCSE 3213", "ADVANCED OBJECT-ORIENTED PROGRAMMING WITH JAVA"),
        (3, "2", "BCSE 3214", "SOFTWARE ARCHITECTURE"),
        (4, "2", "BCIT 4264", "PROJECT II (SYSTEM DEVELOPMENT)"),
        (4, "2", "BCSE 4221", "SOFTWARE ENGINEERING PROFESSION AND ETHICS"),
        (4, "2", "BCSE 4222", "SOFTWARE MAINTENANCE AND EVOLUTION"),
        (4, "2", "BCSE 4224", "COMPONENT BASED SOFTWARE DEVELOPMENT"),
        (4, "2", "BCSC 3225", "ARTIFICIAL INTELLIGENCE"),
        (4, "2", "BCIT 4261", "SYSTEM SECURITY AND AUDIT"),
        (4, "2", "BCSE 4225", "ADVANCED BACK-END WEB DEVELOPMENT"),
    ],
    "BDAT": [
        (1, "2", "BSTA 1203", "PROBABILITY AND STATISTICS I"),
        (1, "2", "BCSC 1204", "DATA STRUCTURES AND ALGORITHMS"),
        (1, "2", "BMAT 1204", "DISCRETE MATHEMATICS"),
        (1, "2", "BMAT 1205", "CALCULUS I"),
        (1, "2", "BCIT 1208", "COMPUTER NETWORKS"),
        (1, "2", "BCIT 1210", "DATABASE MANAGEMENT SYSTEMS"),
        (1, "2", "BENT 1207", "ENTREPRENEURSHIP SKILLS"),
        (2, "2", "BDSC 2203", "DATA PREPARATION"),
        (2, "2", "BSTA 2206", "PROBABILITY AND STATISTICS III"),
        (2, "2", "BCSC 2207", "SCIENTIFIC COMPUTING"),
        (2, "2", "BCIT 2218", "INTERNET APPLICATION PROGRAMMING"),
        (2, "2", "BSTA 2235", "LINEAR MODELS II"),
        (2, "2", "BCSC 2256", "DATA COMMUNICATION"),
        (2, "2", "BCIT 2214", "SOFTWARE ENGINEERING"),
        (3, "2", "BDSC 3208", "DATA VISUALIZATION"),
        (3, "2", "BDSC 3217", "VIDEO ANALYTICS"),
        (3, "2", "BSTA 3253", "RESEARCH METHODS"),
        (3, "2", "BDSC 3211", "TEXT ANALYTICS"),
        (3, "2", "BDSC 3212", "DATA ENGINEERING"),
        (3, "2", "BCIT 3260", "RESEARCH METHODS FOR IT"),
        (3, "2", "BSTA 3239", "ECONOMETRICS"),
        (4, "2", "BSTA 4248", "STATISTICS AND BIG DATA ANALYTICS"),
        (4, "2", "BCSC 4235", "DATA MINING"),
        (4, "2", "BDSC 4219", "CYBERSECURITY AND DATA SCIENCE"),
        (4, "2", "BSTA 4251", "PROJECT II (RESEARCH PROJECT REPORT)"),
        (4, "2", "BDSC 4215", "STRATEGIC INFORMATION SYSTEMS"),
        (4, "2", "BCIT 4266", "COMPUTING LAW AND ETHICS"),
    ],
    "BSCAS": [
        (1, "2", "BSTA 1203", "PROBABILITY AND STATISTICS I"),
        (1, "2", "BPHY 1203", "PHYSICS"),
        (1, "2", "BMAT 1205", "CALCULUS I"),
        (1, "2", "BMAT 1204", "DISCRETE MATHEMATICS"),
        (1, "2", "BCSC 1204", "DATA STRUCTURES AND ALGORITHMS"),
        (1, "2", "BCIT 1210", "DATABASE MANAGEMENT SYSTEMS"),
        (1, "2", "BENT 1207", "ENTREPRENEURSHIP SKILLS"),
        (2, "2", "BSTA 2237", "ECONOMETRICS I"),
        (2, "2", "BSTA 2235", "LINEAR MODELS II"),
        (2, "2", "BSTA 2207", "OPERATIONS RESEARCH I"),
        (2, "2", "BSTA 2206", "PROBABILITY AND STATISTICS III"),
        (2, "2", "BMAT 2210", "LINEAR ALGEBRA II"),
        (2, "2", "BCSC 2207", "SCIENTIFIC COMPUTING"),
        (2, "2", "BMAT 2217", "VECTOR ANALYSIS"),
        (3, "2", "BMAT 3213", "NUMERICAL ANALYSIS"),
        (3, "2", "BSTA 3253/BCIT 3260", "RESEARCH METHODS"),
        (3, "2", "BSTA 3221", "THEORY OF ESTIMATION"),
        (3, "2", "BSTA 3219", "ECONOMIC AND SOCIAL STATISTICS"),
        (3, "2", "BSTA 3213", "STOCHASTIC PROCESSES"),
        (3, "2", "BSTA 3228", "SURVIVAL MODELS"),
        (3, "2", "BSTA 4147", "HYPOTHESIS TESTING"),
        (4, "2", "BSTA 4251", "PROJECT II"),
        (4, "2", "BSTA 4267", "DESIGN AND ANALYSIS OF CLINICAL TRIALS"),
        (4, "2", "BSTA 4218", "NON-PARAMETRIC AND ROBUST METHODS"),
        (4, "2", "BSTA 4254", "CATEGORICAL DATA ANALYSIS"),
        (4, "2", "BSTA 4248", "STATISTICS AND BIG DATA ANALYTICS"),
        (4, "2", "BCSC 4248", "DATA SCIENCE"),
        (4, "2", "BSTA 4229", "BAYESIAN DATA ANALYSIS"),
    ],
    "BSIT": [
        (1, "2", "BMAT 1204", "DISCRETE MATHEMATICS"),
        (1, "2", "BMAT 1205", "CALCULUS I"),
        (1, "2", "BSTA 1203", "PROBABILITY AND STATISTICS I"),
        (1, "2", "BCSC 1204", "DATA STRUCTURES AND ALGORITHMS"),
        (1, "2", "BCIT 1208", "COMPUTER NETWORKS"),
        (1, "2", "BCIT 1210", "DATABASE MANAGEMENT SYSTEMS"),
        (1, "2", "BENT 1207", "ENTREPRENEURSHIP SKILLS"),
        (2, "2", "BCSC 2207", "SCIENTIFIC COMPUTING"),
        (2, "2", "BSTA 2235", "LINEAR MODELS II"),
        (2, "2", "BSTA 2207", "OPERATIONS RESEARCH I"),
        (2, "2", "BSTA 2206", "PROBABILITY AND STATISTICS III"),
        (2, "2", "BCIT 2219", "MANAGEMENT INFORMATION SYSTEMS"),
        (2, "2", "BCIT 2217", "OBJECT ORIENTED PROGRAMMING II"),
        (2, "2", "BSTA 3210", "STATISTICAL DATA ANALYSIS"),
        (3, "2", "BCIT 3237", "ELECTRONIC COMMERCE"),
        (3, "2", "BSTA 3253", "RESEARCH METHODS FOR IT"),
        (3, "2", "BSTA 3221", "THEORY OF ESTIMATION"),
        (3, "2", "BCSC 3225", "ARTIFICIAL INTELLIGENCE"),
        (3, "2", "BCIT 3262", "DATABASE PROGRAMMING"),
        (3, "2", "BMAT 3213", "NUMERICAL ANALYSIS"),
        (4, "2", "BCIT 3242", "ADVANCED DATABASE MANAGEMENT SYSTEMS"),
        (4, "2", "BCIT 4264", "PROJECT II"),
        (4, "2", "BSTA 4218", "NON-PARAMETRIC AND ROBUST METHODS"),
        (4, "2", "BSCC 4250", "NETWORK PROGRAMMING"),
        (4, "2", "BSCC 4227", "DATA SCIENCE"),
        (4, "2", "BSTA 4105", "DESIGN AND ANALYSIS OF SAMPLE SURVEY"),
    ],
    "BASE": [
        (1, "2", "BFN 1235", "FINANCIAL ACCOUNTING"),
        (1, "2", "BMAT 1204", "DISCRETE MATHEMATICS"),
        (1, "2", "BMAT 1205", "CALCULUS I"),
        (1, "2", "BSTA 1203", "PROBABILITY AND STATISTICS I"),
        (1, "2", "BECO 1202", "PRINCIPLES OF MACROECONOMICS"),
        (1, "2", "BENT 1207", "ENTREPRENEURSHIP SKILLS"),
        (1, "2", "BCIT 1210", "DATABASE MANAGEMENT SYSTEMS"),
        (2, "2", "BFIN 2224", "PUBLIC FINANCE AND TAXATION"),
        (2, "2", "BECO 2204", "INTERMEDIATE MACROECONOMICS"),
        (2, "2", "BSTA 2207", "OPERATIONS RESEARCH I"),
        (2, "2", "BSTA 2206", "PROBABILITY AND STATISTICS III"),
        (2, "2", "BSTA 2235", "LINEAR MODELS II"),
        (2, "2", "BSTA 2237", "ECONOMETRICS I"),
        (3, "2", "BECO 3223/3221", "ADVANCED MACROECONOMIC THEORY"),
        (3, "2", "BSTA 3221", "THEORY OF ESTIMATION"),
        (3, "2", "BSTA 3220", "ECONOMIC AND SOCIAL STATISTICS"),
        (3, "2", "BSTA 3213", "STOCHASTIC PROCESSES"),
        (3, "2", "BBA 3204", "MONETARY THEORY AND PRACTICE"),
        (3, "2", "BSTA 3253", "RESEARCH METHODS"),
        (3, "2", "BSTA 4147", "HYPOTHESIS TESTING"),
        (3, "2", "BACC 2105", "COST ACCOUNTING"),
        (4, "2", "BECO 4217", "TRANSPORT ECONOMICS"),
        (4, "2", "BECO 4113", "ENVIRONMENTAL ECONOMICS"),
        (4, "2", "BSTA 4248", "STATISTICS AND BIG DATA ANALYTICS"),
        (4, "2", "BSTA 4251", "PROJECT II"),
        (4, "2", "BECO 3212", "WELFARE ECONOMICS"),
    ],
    "BSACC": [
        (1, "2", "BENT 1207", "ENTREPRENEURSHIP SKILLS"),
        (1, "2", "BLAW 1201", "BUSINESS LAW"),
        (1, "2", "BMAT 1203", "FUNDAMENTALS OF MATHEMATICS"),
        (1, "2", "BFIN 1235", "FINANCIAL ACCOUNTING"),
        (1, "2", "BECO 1202", "PRINCIPLES OF MACROECONOMICS"),
        (2, "2", "BSTA 2207", "OPERATIONS RESEARCH I"),
        (2, "2", "BACC 2208", "PRINCIPLES OF TAXATION"),
        (2, "2", "BACC 2207", "ACCOUNTING FOR LIABILITIES AND EQUITY"),
        (2, "2", "BACC 2223", "ACCOUNTING INFORMATION SYSTEMS"),
        (2, "2", "BMGT 1201", "PRINCIPLES AND PRACTICE OF MANAGEMENT"),
        (3, "2", "BACC 3226", "FINANCIAL REPORTING AND ANALYSIS"),
        (3, "2", "BACC 3212", "COMPUTERISED ACCOUNTING"),
        (3, "2", "BACC 3210", "AUDITING & ASSURANCE"),
        (3, "2", "BBCU 3201", "RESEARCH METHODS"),
        (4, "2", "BACC 4229", "ACCOUNTING FOR SPECIALISED & PUBLIC SECTOR ENTITIES"),
        (4, "2", "BACC 4225", "ACCOUNTING FOR DERIVATIVES & HEDGES"),
        (4, "2", "BBCU 4208", "RESEARCH PROJECT II"),
        (4, "2", "BACC 4209", "CONTEMPORARY ISSUES IN ACCOUNTING"),
    ],
    "BBFI": [
        (1, "2", "BECO 1202", "PRINCIPLES OF MACROECONOMICS"),
        (1, "2", "BFIN 1235", "FINANCIAL ACCOUNTING"),
        (1, "2", "BLAW 1201", "BUSINESS LAW"),
        (1, "2", "BENT 1207", "ENTREPRENEURSHIP SKILLS"),
        (1, "2", "BMGT 1201", "PRINCIPLES AND PRACTICE OF MANAGEMENT"),
        (2, "2", "BBAN 2213", "BANK LENDING AND CREDIT ADMINISTRATION"),
        (2, "2", "BBFI Y2 S2", "FINANCIAL ECONOMETRICS II"),
        (2, "2", "BBFI Y2 S2", "FINANCIAL ETHICS STANDARDS AND REGULATIONS"),
        (2, "2", "BBFI Y2 S2", "PUBLIC FINANCE AND TAXATION"),
        (2, "2", "BBFI Y2 S2", "ALTERNATIVE INVESTMENT ANALYSIS"),
        (3, "2", "BFIN 3217", "CORPORATE FINANCE"),
        (3, "2", "BBAN 3205", "MONETARY THEORY AND PRACTICE"),
        (3, "2", "BMGT 1201", "PRINCIPLES AND PRACTICE OF MANAGEMENT"),
        (3, "2", "BBCU 3201", "RESEARCH METHODS"),
        (3, "2", "BBAN 3217", "CUSTOMER RELATIONS MANAGEMENT IN BANKING INSTITUTIONS"),
        (4, "2", "BFIN 4219", "ALTERNATIVE INVESTMENTS"),
        (4, "2", "BFIN 4203", "DERIVATIVES ANALYSIS & VALUATION"),
        (4, "2", "BBCU 4208", "RESEARCH PROJECT II"),
        (4, "2", "BMFI 4210", "CONTEMPORARY ISSUES IN MANAGING BANKING INSTITUTIONS"),
        (4, "2", "BBAN 4110", "RISK MANAGEMENT IN BANKING"),
    ],
    "BSCFIN": [
        (1, "2", "BFIN 1235", "FINANCIAL ACCOUNTING"),
        (1, "2", "BMAT 1203", "FUNDAMENTALS OF MATHEMATICS"),
        (1, "2", "BLAW 1201", "BUSINESS LAW"),
        (1, "2", "BECO 1202", "PRINCIPLES OF MACROECONOMICS"),
        (1, "2", "BENT 1207", "ENTREPRENEURSHIP SKILLS"),
        (2, "2", "BSTA 2207", "OPERATIONS RESEARCH I"),
        (2, "2", "BACC 2207", "ACCOUNTING FOR LIABILITIES AND EQUITY"),
        (2, "2", "BACC 3214", "COMPUTERIZED ACCOUNTING"),
        (2, "2", "BFIN 2221", "FINANCIAL ECONOMETRICS II"),
        (2, "2", "BASC 2206", "FINANCIAL MATHEMATICS II"),
        (3, "2", "BFIN 3217", "CORPORATE FINANCE"),
        (3, "2", "BFIN 3224", "RESEARCH METHODS IN FINANCE"),
        (3, "2", "BFIN 3218", "EQUITY ANALYSIS AND VALUATION"),
        (3, "2", "BFIN 3213", "FINANCIAL MARKET LAWS AND REGULATIONS"),
        (3, "2", "BACC 3226", "FINANCIAL REPORTING & ANALYSIS"),
        (4, "2", "BFIN 4219", "ALTERNATIVE INVESTMENT ANALYSIS"),
        (4, "2", "BFIN 4214", "CONTEMPORARY ISSUES IN FINANCE AND INVESTMENTS"),
        (4, "2", "BBCU 4208", "RESEARCH PROJECT II"),
        (4, "2", "BFIN 4208", "PENSION AND OTHER BENEFITS"),
    ],
}


class Command(BaseCommand):
    help = "Seed units for selected courses using curated data."

    def handle(self, *args, **options):
        created = 0
        updated = 0
        missing_courses = []

        for course_code, entries in COURSE_UNITS.items():
            course = Course.objects.filter(code=course_code).first()
            if not course:
                missing_courses.append(course_code)
                continue

            for year, sem, code, name in entries:
                obj, was_created = Unit.objects.update_or_create(
                    course=course,
                    code=code,
                    defaults={
                        "name": name,
                        "year_of_study": year,
                        "semester": str(sem),
                        "is_active": True,
                    },
                )
                if was_created:
                    created += 1
                else:
                    updated += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Units processed. Created: {created}, Updated: {updated}"
            )
        )
        if missing_courses:
            self.stdout.write(
                self.style.WARNING(
                    "Courses not found (skipped): " + ", ".join(sorted(set(missing_courses)))
                )
            )
