import re
from django.core.management.base import BaseCommand
from apps.courses.models import Course, Unit


TEXT = """
Faculty of Computing and Information Technology (CIT)
Department of Computer Science
BSc. Computer Science (BCS)

Year 1 Semester 2: DIGITAL LOGIC AND ELECTRONICS (BPHY 1204), DATA STRUCTURES AND ALGORITHMS (BCSC 1204), ELECTRONICS I (BPHY 1205), PROBABILITY AND STATISTICS I (BSTA 1203), DISCRETE MATHEMATICS (BMAT 1204), CALCULUS I (BMAT 1205), STRUCTURED PROGRAMMING LAB (BCSE 1203), COMPUTER APPLICATIONS (SSP) (BUCI 1104), COMPUTER DESIGN AND ORGANIZATION (SSP) (BCSC 2103), SYSTEM ANALYSIS AND DESIGN (SSP) (BCIT 2112), LINEAR ALGEBRA (SSP) (BMAT 2109), INTRODUCTION TO PROGRAMMING (SSP) (BCSC 1102), COMMUNICATION SKILLS (SSP) (BUCI 1101), LIFE SKILLS (SSP) (BUCI 1102), BASIC MATHEMATICS (SSP) (BMAT 1101)

Year 2 Semester 2: DATABASE MANAGEMENT SYSTEMS (BCIT 1210), COMPUTER NETWORKS (BCIT 1208), OBJECT ORIENTED PROGRAMMING II (BCIT 2217), SCIENTIFIC COMPUTING (BCSC 2207), INTERNET APPLICATION PROGRAMMING (BCIT 2218), SOFTWARE ENGINEERING (BCIT 2214), ENTREPRENEURSHIP SKILLS (BENT 1207)

Year 3 Semester 2: COMPILER CONSTRUCTION AND DESIGN (BCSC 3220), QUANTUM COMPUTER SCIENCE (BCSC 3212), MOBILE APPLICATION DEVELOPMENT (BCIT 3238), DATABASE PROGRAMMING (BCIT 3262), SYSTEM SECURITY AND AUDIT (BCIT 4261), RESEARCH METHODS FOR IT (BCIT 3260), ARTIFICIAL INTELLIGENCE (BCSC 3225)

Year 4 Semester 2: COMPUTER GRAPHICS (BCSC 4234), COMPUTING LAW AND ETHICS (BCIT 4266), PROJECT II (SYSTEM DEVELOPMENT) (BCIT 4264), DATA SCIENCE (BSCS 4227), EXPERT SYSTEMS (BCSC 4232), PATTERN RECOGNITION (BCSC 4248), NETWORK PROGRAMMING (BCSC 4250)

Diploma in Computer Science (DCS)

Year 1 Semester 2: Apply Business Maths and Statistics (DCS 1.20412 551 10A), Cooperative Practices (DCS 1.20412 551 22A), Apply Mathematics for Computer Science (DCS 1.20613 554 10A), Networking and Distributed Systems (DCS 1.20613 554 03A), Graphics Design (DCS 1.20613 554 04A)

Department of Information Technology
BIT (Bachelor of Information Technology)

Year 1 Semester 2: ENTREPRENEURSHIP SKILLS (BENT 1207), CALCULUS I (BMAT 1205), DATA COMMUNICATION AND COMPUTER NETWORKS (BCIT 1202), DATABASE MANAGEMENT SYSTEMS (BCIT 1210), DISCRETE MATHEMATICS (BMAT 1204), DATA STRUCTURES AND ALGORITHMS (CSC 1204), STRUCTURED PROGRAMMING LAB (CSE 1203)

Year 2 Semester 2: ADVANCED OPERATING SYSTEMS (BCIT 2230), COMPUTER AIDED ART AND DESIGN (BCSC 2205), OBJECT ORIENTED PROGRAMMING II (BCIT 2217), DIGITAL LOGIC AND ELECTRONICS (BPHY 1204), PROBABILITY AND STATISTICS I (BSTA 1203), SOFTWARE ENGINEERING (BCIT 2214), NETWORKS AND SYSTEMS ADMINISTRATION (BCIT 2213)

Year 3 Semester 2: MOBILE APPLICATION DEVELOPMENT (BCIT 3238), ELECTRONIC COMMERCE (BCIT 3237), ADVANCED DATABASE MANAGEMENT SYSTEMS (BCIT 3242), ARTIFICIAL INTELLIGENCE (BCSC 3225), RESEARCH METHODS FOR IT (BCIT 3260), DISTRIBUTED SYSTEMS (BCIT 3265), MULTIMEDIA SYSTEMS (BCIT 3244)

Year 4 Semester 2: DATA SCIENCE (BCSC 4227), INFORMATION SYSTEMS AUDIT (BCIT 4255), KNOWLEDGE BASED SYSTEMS (BCSC 4231), COMPUTING LAW AND ETHICS (BCIT 4266), PROJECT II (SYSTEM DEVELOPMENT) (BCIT 4264)

BBIT (Bachelor of Business Information Technology)

Year 1 Semester 2: INTRODUCTION TO INFORMATION SYSTEMS (BCIT 1207), PRINCIPLES AND PRACTICE OF MANAGEMENT (BMGT 1201), BUSINESS LAW (BLAW 1201), PRINCIPLES OF MARKETING (BMKT 1202), ENTREPRENEURSHIP SKILLS (BENT 1207)

Year 2 Semester 1 (SSP): SYSTEMS ANALYSIS AND DESIGN (BCIT 2112), COMMUNICATION SKILLS (BUCI 1101), INTRODUCTION TO PROGRAMMING (BCSC 1102), PRINCIPLES OF MICROECONOMICS (BECO 1101), STATISTICS (BSTA 2101), LIFE SKILLS (BUCI 1102), COOPERATIVE PHILOSOPHY (BUCI 1105), DATABASE MANAGEMENT SYSTEMS (BCIT 1210), MANAGEMENT INFORMATION SYSTEMS (BCIT 2219)

Year 2 Semester 2: COMPUTER NETWORKS (BCIT 1208), DATABASE MANAGEMENT SYSTEMS (BCIT 1210), PRINCIPLES OF MACROECONOMICS (BECO 1202), MANAGEMENT INFORMATION SYSTEMS (BCIT 2219), MATHEMATICS II (BMAT 1207)

Year 3 Semester 2: OBJECT ORIENTED PROGRAMMING (BCIT 2122), RESEARCH METHODS FOR IT (BCIT 3260), ELECTRONIC COMMERCE (BCIT 3237), WEB DEVELOPMENT (BCIT 2132), PRINCIPLES OF MICROECONOMICS (SSP) (BECO 1101), MATHEMATICS I (SSP) (BMAT 1102), COMMUNICATION SKILLS (SSP) (BUCI 1101), LIFE SKILLS (SSP) (BUCI 1102), COOPERATIVE PHILOSOPHY (SSP) (BUCI 1105)

Year 4 Semester 2: FINANCIAL ETHICS AND STANDARDS (BFIN 2225), ICT COMMERCIALIZATION (BCIT 4254), INFORMATION SYSTEMS AUDIT (BCIT 4255), PROJECT II (SYSTEM DEVELOPMENT) (BCIT 4264), MOBILE COMPUTING (BCSC 4214), SIMULATION AND MODELLING (BCSC 4126), ENTREPRENEURSHIP SKILLS (SSP) (BENT 1207), PRINCIPLES AND PRACTICE OF MANAGEMENT (SSP) (BMGT 1201)

Diploma in Information Technology (DIT)

Year 1 Semester 2: Cooperative Practices (DIT 1.2 0031 441 05A), Computer Software (DIT 1.2 0619 451 06A), Network Design and Management (DIT 1.2 0612 451 07A), Computer Programming Principles (DIT 1.2 0613 451 05A), Computerized Database System (DIT 1.2 0612 451 08A), Discrete Mathematical Concepts (DIT 1.2 0541 541 01A)

Year 2 Semester 2: WEB ENGINEERING(CLOUD AND MOBILE) (DIT 2.2 DCIT 1208), NETWORK DESIGN AND SETUP (DIT 2.2 DCSC 2212), PROJECT WORK ( DOCUMENTATION AND SYSTEM IMPLEMENTATION) (DIT 2.2 DCIT 2215), EVENT DRIVEN PROGRAMMING (DIT 2.2 DCSC 2207), DIGITAL ELECTRONICS CONSTRUCTION (DIT 2.2 DCSC 2210)

Diploma in Cyber Security (DCY)

Year 1 Semester 2: Install and Configure Linux (DCY 1.2 0612554 05A), Secure Software Application (DCY 1.2 0612554 06A), Apply Cooperative Practices (DCY 1.2 0612554 03A)

Year 2 Semester 2: Security Assessment and Testing (DCY 2.2 DICY 2218), Security Operations management (DCY 2.2 DICY 2219)

Department of Software Engineering
BSEN (Bachelor of Software Engineering)

Year 1 Semester 2: STRUCTURED PROGRAMMING LAB (BCSE 1203), DATA STRUCTURES AND ALGORITHMS (BCSC 1204), DISCRETE MATHEMATICS (BMAT 1204), CALCULUS I (BMAT 1205), PROBABILITY AND STATISTICS I (BSTA 1203), DIGITAL LOGIC AND ELECTRONICS (BPHY 1204)

Year 2 Semester 2: DATABASE MANAGEMENT SYSTEMS (BCIT 1210), SOFTWARE REQUIREMENTS ENGINEERING (BCSE 2206), SOFTWARE METRICS (BCSE 2207), INTERNET APPLICATION PROGRAMMING (BCIT 2218), FUNDAMENTALS OF OBJECT ORIENTED PROGRAMMING WITH JAVA (BCSE 2208), DATABASE PROGRAMMING (BCIT 3262), ENTREPRENEURSHIP SKILLS (BENT 1207)

Year 3 Semester 2: COMPILER CONSTRUCTION AND DESIGN (BCSC 3220), MOBILE APPLICATION DEVELOPMENT (BCIT 3238), RESEARCH METHODS FOR IT (BCIT 3260), SOFTWARE VERIFICATION AND VALIDATION (BCSE 3211), OBJECT ORIENTED ANALYSIS AND DESIGN WITH UML (BCSE 3212), ADVANCED OBJECT-ORIENTED PROGRAMMING WITH JAVA (BCSE 3213), SOFTWARE ARCHITECTURE (BCSE 3214)

Year 4 Semester 2: PROJECT II (SYSTEM DEVELOPMENT) (BCIT 4264), SOFTWARE ENGINEERING PROFESSION AND ETHICS (BCSE 4221), SOFTWARE MAINTENANCE AND EVOLUTION (BCSE 4222), COMPONENT BASED SOFTWARE DEVELOPMENT (BCSE 4224), ARTIFICIAL INTELLIGENCE (BCSC 3225), SYSTEM SECURITY AND AUDIT (BCIT 4261), ADVANCED BACK-END WEB DEVELOPMENT (BCSE 4225)

Department of Data Science
BDAT (Bachelor of Data Science)

Year 1 Semester 2: PROBABILITY AND STATISTICS I (BSTA 1203), DATA STRUCTURES AND ALGORITHMS (BCSC 1204), DISCRETE MATHEMATICS (BMAT 1204), CALCULUS I (BMAT 1205), COMPUTER NETWORKS (BCIT 1208), DATABASE MANAGEMENT SYSTEMS (BCIT 1210), ENTREPRENEURSHIP SKILLS (BENT 1207)

Year 2 Semester 2: DATA PREPARATION (BDSC 2203), PROBABILITY AND STATISTICS III (BSTA 2206), SCIENTIFIC COMPUTING (BCSC 2207), INTERNET APPLICATION PROGRAMMING (BCIT 2218), LINEAR MODELS II (BSTA 2235), DATA COMMUNICATION (BCSC 2256), SOFTWARE ENGINEERING (BCIT 2214)

Year 3 Semester 2: DATA VISUALIZATION (BDSC 3208), VIDEO ANALYTICS (BDSC 3217), RESEARCH METHODS (BSTA 3253), TEXT ANALYTICS (BDSC 3211), DATA ENGINEERING (BDSC 3212), RESEARCH METHODS FOR IT (BCIT 3260), ECONOMETRICS (BSTA 3239)

Year 4 Semester 2: STATISTICS AND BIG DATA ANALYTICS (BSTA 4248), DATA MINING (BCSC 4235), CYBERSECURITY AND DATA SCIENCE (BDSC 4219), PROJECT II (RESEARCH PROJECT REPORT) (BSTA 4251), STRATEGIC INFORMATION SYSTEMS (BDSC 4215), COMPUTING LAW AND ETHICS (BCIT 4266)

BSCAS (BSc. Applied Statistics)

Year 1 Semester 2: PROBABILITY AND STATISTICS I (BSTA 1203), PHYSICS (BPHY 1203), CALCULUS I (BMAT 1205), DISCRETE MATHEMATICS (BMAT 1204), DATA STRUCTURES AND ALGORITHMS (BCSC 1204), DATABASE MANAGEMENT SYSTEMS (BCIT 1210), ENTREPRENEURSHIP SKILLS (BENT 1207)

Year 2 Semester 2: ECONOMETRICS I (BSTA 2237), LINEAR MODELS II (BSTA 2235), OPERATIONS RESEARCH I (BSTA 2207), PROBABILITY AND STATISTICS III (BSTA 2206), LINEAR ALGEBRA II (BMAT 2210), SCIENTIFIC COMPUTING (BCSC 2207), VECTOR ANALYSIS (BMAT 2217)

Year 3 Semester 2: NUMERICAL ANALYSIS (BMAT 3213), RESEARCH METHODS (BSTA 3253/BCIT 3260), THEORY OF ESTIMATION (BSTA 3221), ECONOMIC AND SOCIAL STATISTICS (BSTA 3219), STOCHASTIC PROCESSES (BSTA 3213), SURVIVAL MODELS (BSTA 3228), HYPOTHESIS TESTING (BSTA 4147)

Year 4 Semester 2: PROJECT II (BSTA 4251), DESIGN AND ANALYSIS OF CLINICAL TRIALS (BSTA 4267), NON-PARAMETRIC AND ROBUST METHODS (BSTA 4218), CATEGORICAL DATA ANALYSIS (BSTA 4254), STATISTICS AND BIG DATA ANALYTICS (BSTA 4248), DATA SCIENCE (BCSC 4248), BAYESIAN DATA ANALYSIS (BSTA 4229)

BSIT (BSc. Statistics and Information Technology)

Year 1 Semester 2: DISCRETE MATHEMATICS (BMAT 1204), CALCULUS I (BMAT 1205), PROBABILITY AND STATISTICS I (BSTA 1203), DATA STRUCTURES AND ALGORITHMS (BCSC 1204), COMPUTER NETWORKS (BCIT 1208), DATABASE MANAGEMENT SYSTEMS (BCIT 1210), ENTREPRENEURSHIP SKILLS (BENT 1207)

Year 2 Semester 2: SCIENTIFIC COMPUTING (BCSC 2207), LINEAR MODELS II (BSTA 2235), OPERATIONS RESEARCH I (BSTA 2207), PROBABILITY AND STATISTICS III (BSTA 2206), MANAGEMENT INFORMATION SYSTEMS (BCIT 2219), OBJECT ORIENTED PROGRAMMING II (BCIT 2217), STATISTICAL DATA ANALYSIS (BSTA 3210)

Year 3 Semester 2: ELECTRONIC COMMERCE (BCIT 3237), RESEARCH METHODS FOR IT (BSTA 3253), THEORY OF ESTIMATION (BSTA 3221), ARTIFICIAL INTELLIGENCE (BCSC 3225), DATABASE PROGRAMMING (BCIT 3262), NUMERICAL ANALYSIS (BMAT 3213)

Year 4 Semester 2: ADVANCED DATABASE MANAGEMENT SYSTEMS (BCIT 3242), PROJECT II (BCIT 4264), NON-PARAMETRIC AND ROBUST METHODS (BSTA 4218), NETWORK PROGRAMMING (BSCC 4250), DATA SCIENCE (BSCC 4227), DESIGN AND ANALYSIS OF SAMPLE SURVEY (BSTA 4105)
"""


def parse_units(text: str):
    """
    Parse the large text blob into records:
    (course_code, year, semester, unit_code, unit_name)
    """
    records = []
    current_course = None
    course_pattern = re.compile(r"\((?P<code>[A-Z0-9\-]+)\)")
    year_sem_pattern = re.compile(r"Year\s+(?P<year>\d+)\s+Semester\s+(?P<sem>\d+):\s*(?P<body>.+)", re.IGNORECASE)

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        # Detect course header like "BSc. Computer Science (BCS)"
        course_match = course_pattern.search(line)
        if course_match and not line.lower().startswith("year"):
            current_course = course_match.group("code").strip()
            continue

        # Detect year/semester lines
        ys_match = year_sem_pattern.match(line)
        if ys_match and current_course:
            year = int(ys_match.group("year"))
            sem = ys_match.group("sem")
            body = ys_match.group("body")

            # Split units separated by commas
            units_parts = [u.strip() for u in body.split(",") if u.strip()]
            for part in units_parts:
                # take last (...) as code
                code_matches = re.findall(r"\(([^)]+)\)", part)
                if not code_matches:
                    continue
                unit_code = code_matches[-1].strip()
                # name is part before last "("
                name_part = part[: part.rfind("(")].strip(" ,")
                # remove any trailing "(SSP)" etc.
                name_part = re.sub(r"\(.*?\)", "", name_part).strip()
                unit_name = name_part if name_part else unit_code
                records.append((current_course, year, sem, unit_code, unit_name))
    return records


class Command(BaseCommand):
    help = "Seed units with names, year, and semester from the provided curriculum text."

    def handle(self, *args, **options):
        records = parse_units(TEXT)
        created = 0
        updated = 0
        missing_courses = set()

        for course_code, year, sem, code, name in records:
            course = Course.objects.filter(code=course_code).first()
            if not course:
                missing_courses.add(course_code)
                continue
            obj, was_created = Unit.objects.update_or_create(
                course=course,
                code=code,
                defaults={
                    "name": name,
                    "year_of_study": year,
                    "semester": str(sem),
                    "is_active": True,
                },
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Units seeded/updated. Created: {created}, Updated: {updated}"
            )
        )
        if missing_courses:
            self.stdout.write(
                self.style.WARNING(
                    "Courses not found (skipped): " + ", ".join(sorted(missing_courses))
                )
            )
