"""
AI Study Goal Models
Personalized study goals for students
"""

import uuid

from django.conf import settings
from django.db import models

from apps.core.models import TimeStampedModel


class StudyGoal(TimeStampedModel):
    """
    AI-generated personalized study goals for students.
    """

    # Goal type choices
    GOAL_TYPE_CHOICES = [
        ("short_term", "Short-term (Daily/Weekly)"),
        ("medium_term", "Medium-term (Monthly)"),
        ("long_term", "Long-term (Semester/Course)"),
        ("subject_specific", "Subject-specific"),
    ]

    # Status choices
    STATUS_CHOICES = [
        ("active", "Active"),
        ("completed", "Completed"),
        ("cancelled", "Cancelled"),
        ("expired", "Expired"),
    ]

    # Priority choices
    PRIORITY_CHOICES = [
        ("low", "Low"),
        ("medium", "Medium"),
        ("high", "High"),
        ("urgent", "Urgent"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # User who owns this goal
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="study_goals"
    )

    # Goal details
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    goal_type = models.CharField(max_length=20, choices=GOAL_TYPE_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="active")
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default="medium")

    # Target metrics
    target_hours = models.FloatField(null=True, blank=True, help_text="Target study hours")
    target_topics = models.JSONField(default=list, help_text="List of topics to cover")
    target_resources = models.JSONField(default=list, help_text="List of resources to complete")

    # Progress tracking
    progress = models.PositiveIntegerField(default=0, help_text="Progress percentage 0-100")
    completed_hours = models.FloatField(default=0, help_text="Hours completed")
    completed_topics = models.JSONField(default=list, help_text="Completed topics")

    # AI-generated recommendations
    ai_recommendations = models.JSONField(default=dict, help_text="AI suggestions")
    weak_areas = models.JSONField(default=list, help_text="Areas needing improvement")

    # Related course/unit (optional)
    course = models.ForeignKey(
        "courses.Course",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="study_goals"
    )
    unit = models.ForeignKey(
        "courses.Unit",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="study_goals"
    )

    # Deadlines
    start_date = models.DateField(null=True, blank=True)
    target_date = models.DateField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    # Metadata
    is_auto_generated = models.BooleanField(
        default=True,
        help_text="Whether this goal was auto-generated by AI"
    )
    generation_context = models.JSONField(
        default=dict,
        help_text="Data used to generate this goal"
    )

    class Meta:
        app_label = "ai"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["user", "status"]),
            models.Index(fields=["user", "goal_type"]),
            models.Index(fields=["status", "target_date"]),
            models.Index(fields=["user", "-created_at"]),
        ]

    def __str__(self):
        return f"{self.title} ({self.user.email}) - {self.progress}%"

    def mark_complete(self):
        """Mark the goal as completed."""
        from django.utils import timezone
        self.status = "completed"
        self.progress = 100
        self.completed_at = timezone.now()
        self.save()

    def update_progress(self, hours: float = 0, topic: str = None):
        """Update goal progress."""
        if hours > 0:
            self.completed_hours += hours
            if self.target_hours:
                self.progress = min(100, int((self.completed_hours / self.target_hours) * 100))

        if topic and topic not in self.completed_topics:
            self.completed_topics.append(topic)
            # Recalculate progress based on topics
            if self.target_topics:
                self.progress = min(100, int((len(self.completed_topics) / len(self.target_topics)) * 100))

        if self.progress >= 100:
            self.mark_complete()
        else:
            self.save()


class StudyGoalMilestone(TimeStampedModel):
    """
    Milestones within a study goal for tracking progress.
    """

    MILESTONE_TYPE_CHOICES = [
        ("exam", "Exam"),
        ("assignment", "Assignment"),
        ("project", "Project"),
        ("revision", "Revision"),
        ("practice", "Practice"),
        ("checkpoint", "Checkpoint"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Related goal
    study_goal = models.ForeignKey(
        StudyGoal,
        on_delete=models.CASCADE,
        related_name="milestones"
    )

    # Milestone details
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    milestone_type = models.CharField(max_length=20, choices=MILESTONE_TYPE_CHOICES)

    # Due date
    due_date = models.DateField(null=True, blank=True)

    # Status
    is_completed = models.BooleanField(default=False)
    completed_at = models.DateTimeField(null=True, blank=True)

    # Completion percentage
    progress = models.PositiveIntegerField(default=0)

    class Meta:
        app_label = "ai"
        ordering = ["due_date", "created_at"]
        indexes = [
            models.Index(fields=["study_goal", "due_date"]),
            models.Index(fields=["is_completed", "due_date"]),
        ]

    def __str__(self):
        return f"{self.title} ({self.study_goal.title})"

    def mark_complete(self):
        """Mark milestone as completed."""
        from django.utils import timezone
        self.is_completed = True
        self.completed_at = timezone.now()
        self.progress = 100
        self.save()


class GoalReminder(TimeStampedModel):
    """
    Reminders for incomplete study goals.
    """

    REMINDER_TYPE_CHOICES = [
        ("daily", "Daily"),
        ("weekly", "Weekly"),
        ("deadline", "Deadline approaching"),
        ("overdue", "Overdue"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Related goal
    study_goal = models.ForeignKey(
        StudyGoal,
        on_delete=models.CASCADE,
        related_name="reminders"
    )

    # Reminder details
    reminder_type = models.CharField(max_length=20, choices=REMINDER_TYPE_CHOICES)
    scheduled_at = models.DateTimeField()
    sent_at = models.DateTimeField(null=True, blank=True)
    is_sent = models.BooleanField(default=False)

    # Message
    message = models.TextField(blank=True)

    class Meta:
        app_label = "ai"
        ordering = ["scheduled_at"]
        indexes = [
            models.Index(fields=["study_goal", "is_sent"]),
            models.Index(fields=["is_sent", "scheduled_at"]),
        ]

    def __str__(self):
        return f"Reminder for {self.study_goal.title} at {self.scheduled_at}"