# Generated by Django 4.2.29 on 2026-03-26 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3 (Summer)')], max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mid_semester_start', models.DateField(blank=True, null=True)),
                ('mid_semester_end', models.DateField(blank=True, null=True)),
                ('exam_start_date', models.DateField(blank=True, null=True)),
                ('exam_end_date', models.DateField(blank=True, null=True)),
                ('break_start_date', models.DateField(blank=True, null=True)),
                ('break_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_calendars', to='faculties.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_calendars', to='faculties.faculty')),
            ],
            options={
                'verbose_name': 'Academic Calendar',
                'verbose_name_plural': 'Academic Calendars',
                'ordering': ['-year', '-semester'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type', models.CharField(choices=[('lecture', 'Lecture'), ('tutorial', 'Tutorial'), ('lab', 'Laboratory'), ('seminar', 'Seminar'), ('fieldwork', 'Field Work'), ('exam', 'Exam')], default='lecture', max_length=20)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('is_virtual', models.BooleanField(default=False)),
                ('virtual_link', models.URLField(blank=True)),
                ('year_of_study', models.PositiveIntegerField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('weeks', models.JSONField(blank=True, default=list)),
                ('group_name', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('academic_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='calendar.academiccalendar')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='courses.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_timetables', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='courses.unit')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('override_type', models.CharField(choices=[('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('extra', 'Extra Session'), ('moved', 'Moved to New Location')], max_length=20)),
                ('new_start_time', models.TimeField(blank=True, null=True)),
                ('new_end_time', models.TimeField(blank=True, null=True)),
                ('new_building', models.CharField(blank=True, max_length=100)),
                ('new_room', models.CharField(blank=True, max_length=50)),
                ('new_virtual_link', models.URLField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('notify_students', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetable_overrides', to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='calendar.timetable')),
            ],
            options={
                'verbose_name': 'Timetable Override',
                'verbose_name_plural': 'Timetable Overrides',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_type', models.CharField(max_length=50)),
                ('external_tokens', models.JSONField(blank=True, default=dict)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_official_timetable', models.BooleanField(default=True)),
                ('sync_personal_events', models.BooleanField(default=True)),
                ('sync_exams', models.BooleanField(default=True)),
                ('sync_announcements', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule Export',
                'verbose_name_plural': 'Schedule Exports',
            },
        ),
        migrations.CreateModel(
            name='PersonalSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('study', 'Study Session'), ('assignment', 'Assignment Due'), ('exam', 'Exam'), ('club', 'Club Activity'), ('personal', 'Personal'), ('reminder', 'Reminder')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('reminder_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before event to send reminder')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.JSONField(blank=True, default=dict)),
                ('is_private', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_schedules', to='courses.course')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_schedules', to='courses.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Schedule',
                'verbose_name_plural': 'Personal Schedules',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['academic_calendar', 'day', 'start_time'], name='calendar_ti_academi_3d9861_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['unit', 'day'], name='calendar_ti_unit_id_9d4e74_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['instructor', 'day'], name='calendar_ti_instruc_e48ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='personalschedule',
            index=models.Index(fields=['user', 'date'], name='calendar_pe_user_id_721839_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academiccalendar',
            unique_together={('faculty', 'year', 'semester')},
        ),
    ]
