# Generated by Django 4.2.29 on 2026-03-26 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Outlook Calendar'), ('apple', 'Apple Calendar')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('calendar_id', models.CharField(blank=True, max_length=255)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'provider', 'email')},
            },
        ),
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_sync', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.IntegerField(default=30)),
                ('sync_direction', models.CharField(choices=[('import', 'Import only'), ('export', 'Export only'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=20)),
                ('sync_lectures', models.BooleanField(default=True)),
                ('sync_assignments', models.BooleanField(default=True)),
                ('sync_exams', models.BooleanField(default=True)),
                ('sync_study_sessions', models.BooleanField(default=True)),
                ('sync_personal', models.BooleanField(default=True)),
                ('notify_before_events', models.BooleanField(default=True)),
                ('notify_minutes_before', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_sync_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_event_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_all_day', models.BooleanField(default=False)),
                ('attendees', models.JSONField(default=list)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('calendar_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_events', to='calendar_sync.calendaraccount')),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['calendar_account', 'start_time'], name='calendar_sy_calenda_8f7db8_idx')],
                'unique_together': {('calendar_account', 'external_event_id')},
            },
        ),
    ]
