import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyGoal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("short_term", "Short-term (Daily/Weekly)"),
                            ("medium_term", "Medium-term (Monthly)"),
                            ("long_term", "Long-term (Semester/Course)"),
                            ("subject_specific", "Subject-specific"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("target_hours", models.FloatField(blank=True, help_text="Target study hours", null=True)),
                ("target_topics", models.JSONField(default=list, help_text="List of topics to cover")),
                ("target_resources", models.JSONField(default=list, help_text="List of resources to complete")),
                ("progress", models.PositiveIntegerField(default=0, help_text="Progress percentage 0-100")),
                ("completed_hours", models.FloatField(default=0, help_text="Hours completed")),
                ("completed_topics", models.JSONField(default=list, help_text="Completed topics")),
                ("ai_recommendations", models.JSONField(default=dict, help_text="AI suggestions")),
                ("weak_areas", models.JSONField(default=list, help_text="Areas needing improvement")),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_auto_generated",
                    models.BooleanField(default=True, help_text="Whether this goal was auto-generated by AI"),
                ),
                (
                    "generation_context",
                    models.JSONField(default=dict, help_text="Data used to generate this goal"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="study_goals",
                        to="courses.course",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="study_goals",
                        to="courses.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="study_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="ai_studygoa_user_id_933a48_idx"),
                    models.Index(fields=["user", "goal_type"], name="ai_studygoa_user_id_985a74_idx"),
                    models.Index(fields=["status", "target_date"], name="ai_studygoa_status_7a3a42_idx"),
                    models.Index(fields=["user", "-created_at"], name="ai_studygoa_user_id_2f4915_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudyGoalMilestone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("exam", "Exam"),
                            ("assignment", "Assignment"),
                            ("project", "Project"),
                            ("revision", "Revision"),
                            ("practice", "Practice"),
                            ("checkpoint", "Checkpoint"),
                        ],
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "study_goal",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="milestones",
                        to="ai.studygoal",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "created_at"],
                "indexes": [
                    models.Index(fields=["study_goal", "due_date"], name="ai_studygoa_study_g_4ce123_idx"),
                    models.Index(fields=["is_completed", "due_date"], name="ai_studygoa_is_comp_4b9df3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GoalReminder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("deadline", "Deadline approaching"),
                            ("overdue", "Overdue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True)),
                (
                    "study_goal",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="reminders",
                        to="ai.studygoal",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
                "indexes": [
                    models.Index(fields=["study_goal", "is_sent"], name="ai_goalremi_study_g_a8af20_idx"),
                    models.Index(fields=["is_sent", "scheduled_at"], name="ai_goalremi_is_sent_bf6ced_idx"),
                ],
            },
        ),
    ]
