# Generated by Django 4.2.29 on 2026-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='goalreminder',
            new_name='ai_goalremi_study_g_89590a_idx',
            old_name='ai_goalremi_study_g_a8af20_idx',
        ),
        migrations.RenameIndex(
            model_name='goalreminder',
            new_name='ai_goalremi_is_sent_ddd124_idx',
            old_name='ai_goalremi_is_sent_bf6ced_idx',
        ),
        migrations.RenameIndex(
            model_name='studygoal',
            new_name='ai_studygoa_user_id_b1395b_idx',
            old_name='ai_studygoa_user_id_933a48_idx',
        ),
        migrations.RenameIndex(
            model_name='studygoal',
            new_name='ai_studygoa_user_id_38bf1d_idx',
            old_name='ai_studygoa_user_id_985a74_idx',
        ),
        migrations.RenameIndex(
            model_name='studygoal',
            new_name='ai_studygoa_status_b2f367_idx',
            old_name='ai_studygoa_status_7a3a42_idx',
        ),
        migrations.RenameIndex(
            model_name='studygoal',
            new_name='ai_studygoa_user_id_c39214_idx',
            old_name='ai_studygoa_user_id_2f4915_idx',
        ),
        migrations.RenameIndex(
            model_name='studygoalmilestone',
            new_name='ai_studygoa_study_g_e668f9_idx',
            old_name='ai_studygoa_study_g_4ce123_idx',
        ),
        migrations.RenameIndex(
            model_name='studygoalmilestone',
            new_name='ai_studygoa_is_comp_590ab8_idx',
            old_name='ai_studygoa_is_comp_4b9df3_idx',
        ),
        migrations.AlterField(
            model_name='goalreminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studygoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studygoalmilestone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
