# Generated by Django 4.2.29 on 2026-03-09 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('faculties', '0001_initial'),
        ('resources', '0004_resourceversion_resourcerequest_courseprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year_of_study', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('max_members', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('completed', 'Completed')], default='active', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='study_groups/covers/')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to='courses.course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_study_groups', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to='faculties.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to='faculties.faculty')),
            ],
            options={
                'verbose_name': 'Study Group',
                'verbose_name_plural': 'Study Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('banned', 'Banned')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='social.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(related_name='study_groups', through='social.StudyGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudyGroupResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='social.studygroup')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_in_groups', to='resources.resource')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_in_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Group Resource',
                'verbose_name_plural': 'Study Group Resources',
                'unique_together': {('group', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='StudyGroupPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_announcement', models.BooleanField(default=False)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_group_posts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.studygroup')),
            ],
            options={
                'verbose_name': 'Study Group Post',
                'verbose_name_plural': 'Study Group Posts',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['group', '-created_at'], name='social_stud_group_i_de58a8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='studygroupmember',
            index=models.Index(fields=['group', 'status'], name='social_stud_group_i_e515ec_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroupmember',
            index=models.Index(fields=['user', 'status'], name='social_stud_user_id_244c30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studygroupmember',
            unique_together={('user', 'group')},
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['status', '-created_at'], name='social_stud_status_ee44fe_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['course', 'status'], name='social_stud_course__cc34fc_idx'),
        ),
    ]
