# Generated by Django 4.2.29 on 2026-03-10 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_studygroup_studygroupmember_studygroup_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='allow_member_invites',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invite_only', 'Invite Only')], default='public', max_length=20),
        ),
        migrations.CreateModel(
            name='StudyGroupInviteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('allow_auto_join', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invite_links', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='social.studygroup')),
            ],
            options={
                'verbose_name': 'Study Group Invite Link',
                'verbose_name_plural': 'Study Group Invite Links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', 'is_active'], name='social_stud_group_i_2ce52e_idx'), models.Index(fields=['token', 'is_active'], name='social_stud_token_a2de3d_idx')],
            },
        ),
    ]
