# Generated by Django 4.2.29 on 2026-03-08 10:01

import uuid

from django.db import migrations, models


def _convert_notification_ids_to_uuid(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    for table in ("notifications_devicetoken", "notifications_notification"):
        schema_editor.execute(
            f'ALTER TABLE "{table}" '
            'ADD COLUMN "id_uuid" uuid DEFAULT gen_random_uuid();'
        )
        schema_editor.execute(
            f'UPDATE "{table}" SET "id_uuid" = gen_random_uuid() '
            'WHERE "id_uuid" IS NULL;'
        )
        schema_editor.execute(
            f'ALTER TABLE "{table}" '
            'ALTER COLUMN "id_uuid" SET NOT NULL;'
        )
        schema_editor.execute(
            f'ALTER TABLE "{table}" '
            f'DROP CONSTRAINT IF EXISTS "{table}_pkey";'
        )
        schema_editor.execute(f'ALTER TABLE "{table}" DROP COLUMN "id";')
        schema_editor.execute(
            f'ALTER TABLE "{table}" '
            'RENAME COLUMN "id_uuid" TO "id";'
        )
        schema_editor.execute(
            f'ALTER TABLE "{table}" '
            'ADD PRIMARY KEY ("id");'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="notificatio_user_id_f0e72c_idx",
            old_name="notificatio_user_id_7c8e5d_fk",
        ),
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="notificatio_device__7b08eb_idx",
            old_name="notificatio_device_4f0c8e_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_created_ae6ed6_idx",
            old_name="notificatio_created_4b4c8e_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_684eac_idx",
            old_name="notificatio_recipie_5d7e9f_idx",
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _convert_notification_ids_to_uuid, reverse_code=migrations.RunPython.noop
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="devicetoken",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="notification",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
