# Generated by Django 4.2.29 on 2026-03-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notificatio_user_id_7c8e5d_fk_notificatio_user_id_f0e72c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('resource_approved', 'Resource Approved'), ('resource_rejected', 'Resource Rejected'), ('new_comment', 'New Comment'), ('comment_reply', 'Comment Reply'), ('new_rating', 'New Rating'), ('new_download', 'New Download'), ('trending', 'Trending Resource'), ('announcement', 'Announcement'), ('report_update', 'Report Update'), ('resource_shared_with_user', 'Resource Shared With User'), ('resource_shared_to_group', 'Resource Shared To Group'), ('system', 'System Notification')], default='system', max_length=50),
        ),
    ]
