# Generated by Django 4.2.29 on 2026-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('resource_approved', 'Resource Approved'), ('resource_rejected', 'Resource Rejected'), ('new_resource', 'New Resource'), ('resource_updated', 'Resource Updated'), ('resource_liked', 'Resource Liked'), ('new_comment', 'New Comment'), ('comment_reply', 'Comment Reply'), ('new_rating', 'New Rating'), ('new_download', 'New Download'), ('trending', 'Trending Resource'), ('announcement', 'Announcement'), ('report_update', 'Report Update'), ('resource_shared_with_user', 'Resource Shared With User'), ('resource_shared_to_group', 'Resource Shared To Group'), ('resource_request', 'Resource Request'), ('inactivity_reminder', 'Engagement Reminder'), ('system', 'System Notification')], default='system', max_length=50),
        ),
    ]
