# Generated by Django 4.2.29 on 2026-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_admin_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('resource_approved', 'Resource Approved'), ('resource_rejected', 'Resource Rejected'), ('new_resource', 'New Resource'), ('resource_updated', 'Resource Updated'), ('resource_liked', 'Resource Liked'), ('new_comment', 'New Comment'), ('comment_reply', 'Comment Reply'), ('new_rating', 'New Rating'), ('new_download', 'New Download'), ('trending', 'Trending Resource'), ('announcement', 'Announcement'), ('report_update', 'Report Update'), ('resource_shared_with_user', 'Resource Shared With User'), ('resource_shared_to_group', 'Resource Shared To Group'), ('resource_request', 'Resource Request'), ('inactivity_reminder', 'Engagement Reminder'), ('system', 'System Notification'), ('admin_user_report', 'Admin: User Report Received'), ('admin_content_report', 'Admin: Content Report Received'), ('admin_new_user_signup', 'Admin: New User Signup'), ('admin_suspicious_activity', 'Admin: Suspicious Activity Detected'), ('admin_system_alert', 'Admin: System Alert'), ('admin_resource_pending_moderation', 'Admin: Resource Pending Moderation'), ('admin_bulk_operation_complete', 'Admin: Bulk Operation Complete'), ('admin_api_threshold_warning', 'Admin: API Threshold Warning'), ('admin_storage_warning', 'Admin: Storage Warning'), ('admin_performance_alert', 'Admin: Performance Alert')], default='system', max_length=50),
        ),
    ]
